### ISSUE TITLE
Allowed symbols in fasta files

### ISSUE THREAD

**Issue by valery-shap** [marbl/parsnp#101]
Hello,
I have the same issue like in #100 but it doesn't help change the reference to only one contig with chromosome.
Could you please tell what symbols are allowed in parsnp? only ACTG or N and U too? does it matter the register?
Valery

**Comment by bkille** [comment]
I believe the way MUSCLE was integrated, it assumes the DNA alphabet of `AGCTNagctn`. That being said, you might still be able to get by with other characters, as not all parts of the DNA are passed through MUSCLE.
