### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'list'

### ISSUE THREAD

**Issue by valery-shap** [marbl/parsnp#102]
Hello,
I have conda version of parsnp 1.5.6
I try to take the reference with 5 contigs and have the same issue as in #87.
when I took only the first contig that contains chromosome, everything worked without errors.
```
Traceback (most recent call last):
  File "/home/miniconda3/envs/parsnp/bin/parsnp", line 1328, in <module>
    if block_spos < chr_spos:

```
Best regards,
Valery

**Comment by bkille** [comment]
Hi @valery-shap, thanks for  pointing this out to us! The most recent version of parsnp, 1.6.1, should have this bug fixed. Please let me know if it is still an issue after updating.

**Comment by valery-shap** [comment]
Ok, thank u. I'll try.

Valery
