### ISSUE TITLE
Fail to force inclusion of all genomes

### ISSUE THREAD

**Issue by zjshi** [marbl/parsnp#104]
Hi, I have been running Parsnp v1.2 on a set of 50 bacterial genomes. 

Here is the command line I used:

parsnp -c -d 102492_50/ -r ./102492_ref.fna

Despite supplying -c flag, Parsnp appears to only use a small subset of input genomes (n=13). Please see the detailed program output below. Thanks in advance for any help you may provide!

|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
*************************************************
SETTINGS:
|-refgenome:	./102492_ref.fna
|-aligner:	libMUSCLE
|-seqdir:	102492_50/
|-outdir:	/raid1/P_2022_01_26_071302778873
|-OS:		Linux
|-threads:	32
*************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from 102492_50/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
  |->[OK]
-->Running PhiPack on LCBs to detect recombination..
  |->[SKIP]
-->Reconstructing core genome phylogeny..
  |->[OK]
-->Creating Gingr input file..
  |->[OK]
-->Calculating wall clock time..
  |->Aligned 13 genomes in 36.94 seconds

<<Parsnp finished! All output available in /raid1/P_2022_01_26_071302778873>>

Validating output directory contents...
	1)parsnp.tree:		newick format tree 			[OK]
	2)parsnp.ggr:		harvest input file for gingr (GUI) 	[OK]
	3)parsnp.xmfa:		XMFA formatted multi-alignment 		[OK]

**Comment by bkille** [comment]
Hi @zjshi! Thanks for opening the issue. It looks like you are using Parsnp v1.2, could you update to v1.6 and let me know if the issue persists? Thanks!

**Comment by zjshi** [comment]
@bkille Yes, this issue is not with higher versions of Parsnp. Thanks!
