### ISSUE TITLE
Option to skip tree building

### ISSUE THREAD

**Issue by hkaspersen** [marbl/parsnp#107]
Hello, and thank you for a great tool!

I am using ParSNP mostly for alignments, so I was wondering if it was possible to perhaps add an option that skips the tree reconstruction? It adds a lot to the runtime of the tool for me.

Thanks in advance!

**Comment by bkille** [comment]
Hi @hkaspersen! The recently added `--skip-phylogeny ` argument in v1.6.1 should do exactly this for you.

**Comment by hkaspersen** [comment]
Thank you forthe swift reply! I will check out that option.
