### ISSUE TITLE
Verify input data

### ISSUE THREAD

**Issue by moorembioinfo** [marbl/parsnp#11]
Hi! 

I'm running parsnp on mac 10.9.1 and I'm getting the error 'Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.' I can't identify any issues with my input files?

Thanks in advance for any advice!

Here is the full command and stdout:

CIMIs-Mac-Pro:harvest-OSX64-v1.0.1 CIMI$ ./parsnp -r ~/Desktop/temp_forB58/LESB58.fasta -d ~/Desktop/Wider_PA_LES/ -p 8 -o ./test
|--Parsnp v1.0--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest

SETTINGS:
|-aligner:	libMUSCLE
|-seqdir:	/Users/CIMI/Desktop/Wider_PA_LES/
|-outdir:	./test
|-OS:		Darwin
|-threads:	8

-->Reading Genome (asm, fasta) files from /Users/CIMI/Desktop/Wider_PA_LES/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Calculating MUMi..
  |->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
**ERROR**
The following command failed:
>>/var/folders/23/zjs7hbts6mnbmslv8fdnzzx40000gn/T/_MEIrg7Jej/parsnp ./test/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

**Comment by treangen** [comment]
Looks like you are not using the latest release, please download v1.2 (https://github.com/marbl/parsnp/releases/tag/v1.2) and rerun. If the issue persists be sure to let me know.

**Comment by moorembioinfo** [comment]
Thanks, that's sorted it! I had upgraded it but left some temporary files in my genome directory :/

Thanks again.
