### ISSUE TITLE
Reference Sequence SNP Call

### ISSUE THREAD

**Issue by hdesale2408** [marbl/parsnp#118]
Hello, I ran parsnp using a 17 whole genomes.  I picked one of these genomes to use as a reference, but kept the sequence file in the directory still.  After running parsnp I looked at the VCF output and it seems that there are SNPs being called when the reference sequence is mapped against itself.  Does this make sense?  It should be the exact same sequence mapped against each other, so why would there be SNPs? 

Thank you!

**Comment by bkille** [comment]
Hi @hdesale2408, 

Sorry for the delay in responding. Yes, there should not be SNPs between the same sequence in an alignment. There have been some [noted](https://github.com/marbl/parsnp/issues/112) (but rare) issues w/ Parsnp incorrectly parsing .gbk files. Did your input contain .gbk/.gb files by any chance?

**Comment by bkille** [comment]
Hi @hdesale2408,

This bug has been fixed in Parsnp 2.0. Please let me know if you continue to experience it!

**Comment by vinicius-santos-bmc** [comment]
The bug is still happening in versions >= 2.0
