### ISSUE TITLE
does parsnp use -gtr from fasttree2 by default... or the fasttree2 default, which is jukes-cantor? 

### ISSUE THREAD

**Issue by Phylloxera** [marbl/parsnp#119]
does parsnp use -gtr from fasttree2 by default... or the fasttree2 default, which is jukes-cantor?

**Comment by bkille** [comment]
Parsnp runs fasttree via the following command:
```
fasttree -nt -quote -gamma -slow -boot 100
```

If you want to run  `fasttree` with your own arguments, you can skip this step in parsnp via `--skip-phylogeny` step, and then use the `parsnp.snps.mblocks` in the output folder as input to FastTree.

**Comment by Phylloxera** [comment]
thanks
