### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by orenavram** [marbl/parsnp#12]
Hello,
I'm trying to run parsnp but for some reason it throws an exception as you can see bellow.
I looked at the source file of parsnp but didn't have found any relevant clue regarding the cause of this problem.
Appreciate if you can assist me here.
Many thanks, Oren 
P.s. usually I use parsnp to align sequences of course, however this time I only need a phylogenetic tree it outputs. So if there's a way I can ask it to only compute the tree for me that'll be fantastic.

---

$ parsnp -r data/NC_000913.fna -g data/NC_000913.gbk -p 8 -d data/ -o parsnp_ref_000913/ -v 
|--Parsnp v1.0--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest

---

SETTINGS:
|-aligner:  libMUSCLE
|-seqdir:   data/
|-outdir:   parsnp_ref_000913/
|-OS:       Linux
|-threads:  8

---

-->Reading Genome (asm, fasta) files from data/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) data/NC_000913.gbk..
  |->[OK]
Traceback (most recent call last):
  File "<string>", line 905, in <module>
IndexError: string index out of range

**Comment by bkille** [comment]
This is an old error with genbank parsing. The new 1.5 version should have this fixed.
