### ISSUE TITLE
Parsnp skips genome without aligning all

### ISSUE THREAD

**Issue by emmannaemeka** [marbl/parsnp#122]
Hello, I am trying to align my genomes. Parsnp identifies that there are 30 fasta files in the folder but only aligns 7. How can I change this?

15:39:18 - INFO - |--Parsnp 1.7.4--|

Ref /Users/emmannaemeka/Documents/benson/phy/parsnp/ref/bongori.fasta
15:40:25 - INFO - 
***********************************
SETTINGS:
|-refgenome:	/Users/emmannaemeka/Documents/benson/phy/parsnp/ref/bongori.fasta
|-genomes:	
	/Users/emmannaemeka/Documents/benson/phy/parsnp/gen/Oranienburg_BCW_3977.fasta
	/Users/emmannaemeka/Documents/benson/phy/parsnp/gen/Molade_PNCS013226.fasta
	...30 more file(s)...
	/Users/emmannaemeka/Documents/benson/phy/parsnp/gen/Oranienburg_CFSAN039536.fasta
	/Users/emmannaemeka/Documents/benson/phy/parsnp/gen/22-120333_S16.fasta
|-aligner:	muscle
|-outdir:	benson_new_ref_phy
|-OS:	Darwin
|-threads:	1
***********************************
    
15:40:25 - INFO - <<Parsnp started>>
15:40:25 - INFO - No genbank file provided for reference annotations, skipping..
15:40:28 - INFO - Recruiting genomes...
15:43:49 - INFO - Running Parsnp multi-MUM search and libMUSCLE aligner...
15:46:12 - INFO - Reconstructing core genome phylogeny...
15:46:17 - INFO - Aligned 7 genomes in 6.97 minutes
15:46:17 - INFO - Parsnp finished! All output available in benson_new_ref_phy

**Comment by pushtimeta** [comment]
How are the genomes selected from the input directory? Not all of the genomes I wanted included are in the tree!
By default, parsnp calculates the MUMi distance between the reference and each of the genomes in the genome directory. All genomes with MUMi distance <= 0.01 are included, all others are discarded. To force all genomes present in the genome dir to be included simply include ‘-c’ as a command-line parameter.

link - [https://harvest.readthedocs.io/en/latest/content/parsnp/faq.html]
