### ISSUE TITLE
No option to use ANI?

### ISSUE THREAD

**Issue by nicolettacommins** [marbl/parsnp#125]
I installed parsnp with conda and I want to use the --use-ani and --min-ani flags. I notice that these options aren't displayed in the help page, but I see them in the source code. When I try to use them I get the error "option --use-ani not recognized." I also noticed that the arg parser takes the flag "--use-ani" but later the code references "args.use_ani". I wanted to test if there was an issue arising from the "_" v. "-" so I tried to install from source. Now I'm running into an issue at this step:

make LDADD=-lMUSCLE-3.7 

Where I get: 
g++ -fopenmp -O2 -m64 -funroll-all-loops -fomit-frame-pointer -ftree-vectorize  -g -O2 -fopenmp -lstdc++ -lpthread -std=gnu++0x -L/broad/hptmp/nikki/parsnp_source/lib -lMUSCLE-3.7   -o parsnp_core parsnp_core-MuscleInterface.o parsnp_core-parsnp.o parsnp_core-LCB.o parsnp_core-LCR.o parsnp_core-TMum.o parsnp_core-Converter.o parsnp_core-iniFile.o -lMUSCLE-3.7 
/bin/ld: cannot find -lMUSCLE-3.7
/bin/ld: cannot find -lMUSCLE-3.7
collect2: error: ld returned 1 exit status
make[1]: *** [parsnp_core] Error 1
make[1]: Leaving directory `/gsap/archive-bacterial/Users/Nikki/sw/parsnp-1.7.4/src'
make: *** [all-recursive] Error 1

I see others have had similar issues but I'm a bit stuck. In any case would appreciate any help in getting the ANI genome recruitment option to work. Thanks!

**Comment by bkille** [comment]
Hi,

What is the version of parsnp you installed from conda?

**Comment by nicolettacommins** [comment]
Now that I look it does seem like conda installed an earlier version of parsnp (1.2). When I try to specify the current version I have incompatibility issues with my system:

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - python=3.7 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

**Comment by bkille** [comment]
Ahhh yes. Looks like you are using Python 2. You can create a new environment with parsnp via 

```
conda create --name parsnp-env "parsnp>=1.7"
```

Make sure you have the bioconda channel set up, though:

https://bioconda.github.io/#usage

**Comment by nicolettacommins** [comment]
I set up my environment with Python 3.7 but you're right that I had messed up my conda channel configuration and I was able to fix it. Thanks for your quick reply and helping me find my problem!
