### ISSUE TITLE
annotating vcf output

### ISSUE THREAD

**Issue by bjh21043** [marbl/parsnp#13]
Is there a way to annotate the vcf output from harvesttools such that the info column will be populated with the ORF locus tag that corresponds to the location of each SNP in the reference genbank file?

**Comment by ondovb** [comment]
Not currently, although this would be a good feature to have and should be straightforward to implement.

**Comment by plasmid02** [comment]
Take a look at snpeff - might be what you are looking for https://github.com/pcingola/SnpEff
