### ISSUE TITLE
Some nodes have a bootstrap value of zero; what does it mean? Can I increase number of bootstrap replicates?

### ISSUE THREAD

**Issue by Phytobacteriology-UPNA** [marbl/parsnp#131]
I am analyzing 59 genomes of very closely related bacteria. Probably because I'm using draft genomes, I get only a 72% of the reference covered by the alignment. Anyway, some of the branches of the resulting phylogenetic tree get a zero or 1 as bootstrap value. Can you help me with any explanation of how can this be? I uploaded a typical tree I get (in newick format)

Also, is there any way to instruct Parsnp to construct the tree using more than 100 bootstrap replicates?

Thanks for the help!

[Pph_59_defC.txt](https://github.com/marbl/parsnp/files/12440905/Pph_59_defC.txt)

**Comment by bkille** [comment]
Hi @Phytobacteriology-UPNA,

Apologies for the late response. In this case, I think you are best off running Parsnp without the phylogeny step with `--skip-phylogeny`. Then, you can use the `parsnp.snps.mblocks` file in your output directory to generate the phylogeny using whichever tool/parameters you'd like.
