### ISSUE TITLE
conda for the latest ParSNP version?

### ISSUE THREAD

**Issue by ajkarloss** [marbl/parsnp#143]
Hi, If you are managing the parsnp conda, could you update it?

**Comment by bkille** [comment]
Yup! There are some minor issues with the build that should be fixed in 2.0.2

I'll close this issue once conda is updated

**Comment by ajkarloss** [comment]
Thanks. Do you have any timeline or?

**Comment by bkille** [comment]
Hi @ajkarloss, thanks for waiting. The release is finally [available on conda](https://bioconda.github.io/recipes/parsnp/README.html). Please reopen the issue if you have any problems obtaining it.
