### ISSUE TITLE
FastTree output tree is missing

### ISSUE THREAD

**Issue by gregorysprenger** [marbl/parsnp#147]
`parsnp.tree` is not created when using `--use-fasttree` with Parsnp. I looked through the `parsnp` python file and only the output of RAxML is renamed to parsnp.tree (via shutil.move). Though, the FastTree phylogeny is placed in `<outputDirectory>/log/fasttree.out`. It is not a _terminating_ error.

I was able to replicate this not only with my test data, but also with the example mers_virus data within this repository.

**Installation:**
```bash
# Bioconda is added to my conda environment and this installs without error
conda create -n parsnp parsnp -y
conda activate parsnp
```

**Commands:**
```bash
# Using FastTree
## ERROR - parsnp.tree:         newick format tree is missing!
parsnp -v -d genomes/ -r ref/England1.fna -o Parsnp2.0.3-fasttree -p 2 -c --use-fasttree
```

```bash
# Using RAxML
## Completes successfully 
parsnp -v -d genomes/ -r ref/England1.fna -o Parsnp2.0.3-fasttree -p 2 -c
```

**Comment by bkille** [comment]
Thank you for the detailed report! I won't be able to address this until next week unfortunately, but it should be an easy fix.
