### ISSUE TITLE
Parsnp requires 2 or more genomes to run, exiting

### ISSUE THREAD

**Issue by yissachar17** [marbl/parsnp#152]
I run this yesterday evening with no problems at all. Everything worked perfectly. Unfortunately, the generated files weren't saved so I tried it again. Now I am getting the below issue **Parsnp requires 2 or more genomes to run, exiting**. Please help. I need this to build a phylogenetic tree. Thanks in advance

parsnp -r referenceGenome/sequence\ \(1\).fasta -d genomes/*.fasta -o parsnpFiles

08:12:32 - INFO - |--Parsnp 2.0.5--|

08:12:32 - INFO -
****************************
SETTINGS:
|-refgenome:    referenceGenome/sequence (1).fasta
|-genomes:
        genomes/174_assembly.fasta
        genomes/198_assembly.fasta
        ...2 more file(s)...
        genomes/66_assembly.fasta
        genomes/93_assembly.fasta
|-aligner:      muscle
|-outdir:       parsnpFiles
|-OS:   Linux
|-threads:      1
****************************

08:12:32 - INFO - <<Parsnp started>>
08:12:32 - INFO - No genbank file provided for reference annotations, skipping..
08:12:32 - INFO - Recruiting genomes...
08:13:48 - ERROR - MUMi file generation failed... use all?
08:13:48 - INFO - Too few genomes to run partitions of size >50. Running all genomes at once.
08:13:48 - CRITICAL - **Parsnp requires 2 or more genomes to run, exiting**

**Comment by bkille** [comment]
Hi @yissachar17!

Just to clarify, you're using the same command and same version as you had previously? If that is the case, could you try outputting to a fresh directory (i.e. `-o parsnpFiles-test`)? 

It shouldn't be the case that existing files in the output directory are messing with your run, but that's the only thing I can think of if nothing else has changed between runs...

Another possibility is the use of spaces and parenthesis in the reference filename. I just tried and was able to run Parsnp w/ `-r "sequence (1).fasta"`, but bash wouldn't allow me to run it with `-r sequence\ (1).fasta`.

**Comment by yissachar17** [comment]
Hi @bkille, thanks for getting back to me.

I managed to resolve the issue.

The issue seemed to be that I was running the parsnp command from a shared directory (with Windows). When I ran parsnp from a non shared directory, it worked!

**Comment by bkille** [comment]
Awesome! Thanks for keeping me posted and let me know if you run into any other issues.

**Comment by dr-joe-wirth** [comment]
I observed similar behavior when running with an existing `-o` directory (i killed previous run). It told me that my genomes were all very small compared to the reference genome, which was not the case.

deleting the pre-existing directory seemed to allow `parsnp` to run; will update with more information when the run finishes.

**Comment by dr-joe-wirth** [comment]
It was something like this (I can double check tomorrow morning). Installed with `conda` and ran on an HPC.

```bash
parsnp -g ref.gbff -d dir/*fna -o parsnp_out -p 24 --use-fasttree
```

I might have spelled the fastrree flag wrong in the block above. I am going from memory.

I killed the job above during "recruiting genomes" step. Then re-ran and it told me all my fastas were 2-4x smaller than the reference. I can recreate the bug and give you the actual output tomorrow. I manually checked genome sizes in biopython, and they are not that small.

I checked this issue bc I got the "2 or more" error. Deleting the output directory before re-running seemed to fix genome recruitment error.

**Comment by dr-joe-wirth** [comment]
Here are steps to recreate the bug:

### run `parsnp`
```bash
parsnp -g ./seqs/GCF_000006945.2.gbff -d ./seqs/*fna -p 24 -o recreate_bug
```

### terminate run during recruitment step
```text
09:03:36 - INFO - |--Parsnp 2.0.5--|

09:03:37 - INFO -
*****************************
SETTINGS:
|-refgenome:    ./seqs/GCF_000006945.2.gbff
|-genomes:
        ./seqs/SAMN07173391.fna
        ./seqs/SAMN07217041.fna
        ...394 more file(s)...
        ./seqs/SAMN37803573.fna
        ./seqs/SAMN37805830.fna
|-aligner:      muscle
|-outdir:       recreate_bug
|-OS:   Linux
|-threads:      24
*****************************

09:03:37 - INFO - <<Parsnp started>>
09:03:50 - INFO - Recruiting genomes...
^C09:03:55 - CRITICAL - Caught request to terminate by user (CTRL+C), exiting now, bye
```

### invoke a second time without deleting directory
#### command
```bash
parsnp -g ./seqs/GCF_000006945.2.gbff -d ./seqs/*fna -p 24 -o recreate_bug
```

#### output
```text
09:04:01 - INFO - |--Parsnp 2.0.5--|

09:04:01 - WARNING - Output directory recreate_bug exists, all results will be overwritten
09:04:01 - INFO -
*****************************
SETTINGS:
|-refgenome:    ./seqs/GCF_000006945.2.gbff
|-genomes:
        ./seqs/SAMN07173391.fna
        ./seqs/SAMN07217041.fna
        ...394 more file(s)...
        ./seqs/SAMN37803573.fna
        ./seqs/SAMN37805830.fna
|-aligner:      muscle
|-outdir:       recreate_bug
|-OS:   Linux
|-threads:      24
*****************************

09:04:01 - INFO - <<Parsnp started>>
09:04:01 - ERROR - File ./seqs/SAMN07173391.fna is 2.01x shorter than reference genome! Skipping...
09:04:01 - ERROR - File ./seqs/SAMN07217041.fna is 2.00x shorter than reference 

< ... note: omitting 300+ lines with more or less the same message ... >

09:04:10 - ERROR - File ./seqs/SAMN37803573.fna is 1.95x shorter than reference genome! Skipping...
09:04:10 - ERROR - File ./seqs/SAMN37805830.fna is 1.96x shorter than reference genome! Skipping...
09:04:10 - CRITICAL - Parsnp requires 2 or more genomes to run, exiting
```

### deleting the output directory solves the problem
data not shown; I can confirm if need be.

### proposed solution
1. `parsnp` checks if the output directory already exists
2. `parsnp` refuses to continue and warns the user the directory already exists
3. implement a `--force` flag
4. `--force` will tell `parsnp` to delete the contents of the existing directory before running

### additional notes
* my first thought that this failed because my genomes are symlinks. i obtained the same error when using the paths to the actual files
* if i run `parsnp` again, the genome sizes get even smaller:
  + after a second run: `09:14:22 - ERROR - File ./seqs/SAMN37805830.fna is 2.94x shorter than reference genome! Skipping...`
  + after a third run: `09:14:57 - ERROR - File ./seqs/SAMN37805830.fna is 3.92x shorter than reference genome! Skipping...`
  + after a fourth run: `09:15:26 - ERROR - File ./seqs/SAMN37805830.fna is 4.91x shorter than reference genome! Skipping...`
  + you get the idea

**Comment by dannagifford** [comment]
I noticed this bug today too. It seems like parsnp runs OK if the directory is empty, but not if there are already the paths parsnp creates: config, log, temp
