### ISSUE TITLE
Index error if file is empty

### ISSUE THREAD

**Issue by mlarjim** [marbl/parsnp#157]
Hi!
I am a big fan of parsnp. I was using v1.7.4 so I decided to update parsnp to v2.0.5. However, I get this error:

```
File "miniconda3/envs/parsnp2/bin/parsnp", line 969, in parse_input_files
    if hdr[0] != ">":
       ~~~^^^
IndexError: string index out of range
```

It is due to an empty file in my genomes directory, but older versions overcome this problem.
Thank you in advance

**Comment by bkille** [comment]
Hi @mlarjim 

So sorry for the late reply. I'll make sure the next update of Parsnp (which I'll release within the next week or so) will automatically check for this. 

In the meantime, if you should be able to get around this by running parsnp with `--validate-input`. That flag will throw out any input file which is empty or has invalid formatting. (It isn't turned on by default as it can lead to longer runtimes for very large inputs).

**Comment by bkille** [comment]
Great! 

Ok for the new issue where it seems to stall on ~9 genomes but works fine on ~300, are the genomes in the group of 9 roughly the same size as those in the group of 300?

Also, thank you for attaching the `--verbose` output! Would you mind pasting the contents of `parsnp_results/parsnpAligner.log`?

**Comment by mlarjim** [comment]
Sorry for the late reply. Apparently one of the genomes was not from the same species, it works fine without the outgroup genome.

Anyway, the content of parsnpAligner.log was
```
MUMS FOUND

```

Thank you Bryce!
