### ISSUE TITLE
Cannot run parsnp with A. thaliana reference.

### ISSUE THREAD

**Issue by abysslover** [marbl/parsnp#16]
Hi, I am trying to utilize parsnp to detect SNPs in three A. thaliana genome assemblies.

I put three A. thaliana assemblies in the ./Genomes folder.
I expect to get results in ./Result folder.

parsnp -r ./TAIR10.fa -d ./Genomes -o ./Result

However, I get the following error. How could I proceed?

ERROR: ref genome sequence ./TAIR10.fa seems to aligned! remove and restart

**Comment by treangen** [comment]
hello,

this message likely suggests you have gap characters somewhere in your alignment; Parsnp will not align previously aligned sequences. Please remove and retry the run.

**Comment by abysslover** [comment]
I have applied a reference genome of A. thaliana and three assemblies of different accessions. I have not tried to align the assemblies against the reference genome before using parsnp.
I could not find any gap characters either in TAIR10 reference genome or in three different assemblies. They are just in FASTA format.

**Comment by abysslover** [comment]
I found the reason.
It is related to the <strong>number of sequences</strong> in the reference genome.
One should provide a single long query sequence for each run of parsnp.
