### ISSUE TITLE
Is recombination filtering already done by default （Version 2.06）?

### ISSUE THREAD

**Issue by Arthurdyu** [marbl/parsnp#163]
Hi，gratitude for your work
In the new version, the option for filtering recombination is not seen (in the old version it was the -x option). 
Is recombination filtering already done by default?

**Comment by bkille** [comment]
The `-x` option still enables the recombination filter, but more recently the CLI help-text for `-x` was accidentally changed to say `xtrafast`. I'll revert that to make it more clear that `-x` enables the recombination filter.

**Comment by bkille** [comment]
Hi @Arthurdyu, thanks for waiting. The new release, [v2.1.0](https://github.com/marbl/parsnp/releases/tag/v2.1.0) has the recombination filtering working with `-x` or `--recomb-filter`. Please let me know if you run into any issues with it.
