### ISSUE TITLE
`--no-recruit` option question

### ISSUE THREAD

**Issue by AstrobioMike** [marbl/parsnp#164]
Heya!

Thanks for updating and maintaining parsnp for us all :) 

I have a quick question that might just be my current lack of understanding. The [2.0 release](https://github.com/marbl/parsnp/releases/tag/v2.0.0) notes that the `--no-recruit` option was added that "skips the recruitment step". But when running parsnp with that flag, it still starts off with "Recruiting genomes...". Is that expected? And if so, what does the `--no-recruit` option do?

Thanks!

**Comment by bkille** [comment]
Hey @AstrobioMike! Thanks for the issue.

The `--no-recruit` is _supposed_ to still filter sequences based on length, but not run the fastani/mumi/mash recruitment. It seems like its not working at the moment, though, so I'll make sure it works as intended in the next release (in a few days).

**Comment by AstrobioMike** [comment]
thanks, @bkille! And thanks again for all your efforts on parsnp 2!

**Comment by bkille** [comment]
Thanks for your patience @AstrobioMike! Just tagged a new release, [v2.1.0](https://github.com/marbl/parsnp/releases/tag/v2.1.0) which renames `--no-recruit` to `--skip-ani-filter` to be more clear. 

```
Filtering:
  -c, --curated         (c)urated genome directory, use all genomes in dir and ignore MUMi.
  --skip-ani-filter     Skip the filtering step which discards inputs based on the ANI/MUMi distance to the reference.
                        Unlike --curated, this will still filter inputs based on their length compared to the reference
```
