### ISSUE TITLE
parsnp.tree format vs newick format

### ISSUE THREAD

**Issue by gotero** [marbl/parsnp#17]
Hi-

The parsnp.tree file I create has a scale bar of 0.05. But when I convert that to a newick formatted file with harvesttools, the scale becomes 5.0 E-5. I'm viewing both files with FigTree. Assuming that the scale is substitutions/site, can someone tell me why it is changing?

Thanks!

Glen

**Comment by treangen** [comment]
hi Glen,

>can someone tell me why it is changing?

Sure thing, allow me to clarify. Harvest scales the branch lengths to take into account the size of the core genome alignment, not just the sites w/ SNPs within the core genome. The parsnp.tree file is the raw output generated by FastTree2, whereas the one you view within Gingr is after the Harvest import, where the adjustment occurs.  This doesn't not affect the branch lengths, just the scale bar. This will now be better described in the documentation.

**Comment by gotero** [comment]
Hi-

Thanks very much for the explanation! 

Can you take a moment to describe 1) how/why branch lengths are scaled to the core genome alignment and 2) why not just scaled to the number of SNPs? 

Thanks!

Glen
