### ISSUE TITLE
A strange error message: Parsnp requires 2 or more genomes to run, exiting

### ISSUE THREAD

**Issue by abysslover** [marbl/parsnp#18]
Hello,

  I am still figuring out how to run parsnp with my datasets. I have two questions.
  (1) could parsnp handle larger genomes such as of A. thaliana and further of H. sapiens rather than those of microorganisms? If you let me know that parsnp does not deal with such large genomes, I could save time and efforts to run parsnp on my datasets.
  (2) In my setting, **Genomes** folder contains 3 genome assemblies of A. thaliana and one of chromosome in A. thaliana genome is used to specify the parameter '-r'. In turn, the command line looks like as follows:

parsnp -r ./TAIR10_chr1.fas -d ./Genomes -o ./Result_chr1 -p 64

  Although the Genomes folder contains 3 genome assemblies, parsnp does not recognize them.
Their file extension was **.fa** and I have tried to change it to **.fna**. Both extensions do not work.
  Could you explain the reason why it does not work?

Euncheon

**Comment by plasmid02** [comment]
I am having a similar issue.  My fasta directory contains 3 files, genbank file created using PROKKA.  Running parsnip v1.2.  I checked program was installed correctly by running the mers49 test set.

    parsnp -d ./fasta_files -g ../../ref.gbk -p 4 -c
    |--Parsnp v1.2--|
    For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
    SETTINGS:
    |-refgenome:	../../ref.gbk.fna
    |-aligner:	libMUSCLE
    |-seqdir:	./fasta_files
    |-outdir:	/P_2016_03_10_105205016053
    |-OS:		Darwin
    |-threads:	4
       
    <<Parsnp started>>
      -->Reading Genome (asm, fasta) files from ./fasta_files..
     |->[OK]
    -->Reading Genbank file(s) for reference (.gbk) ../../ref.gbk..
      |->[OK]
    Parsnp requires 2 or more genomes to run, exiting

**Comment by AnitaVoigt** [comment]
Hey, 
I have the exact same problem. Did you find a solution yet? The genome files have the extension .fa and changing it into .fna didn't solve the problem.
I would be very happy to get a hint to solve the problem. MAny thanks in advance,
Anita

Here is my output

[./parsnp -g ./Ref/E.coli_BL21_complete_genome.gb -d ./Genomes/ -c
|--Parsnp v1.1--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from ./Genomes/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ./Ref/E.coli_BL21_complete_genome.gb..
  |->[OK]
Parsnp requires 2 or more genomes to run, exiting
[] ./Ref/E.coli_BL21_complete_genome.gb.fna

**Comment by treangen** [comment]
>(1) could parsnp handle larger genomes such as of A. thaliana and further of H. sapiens rather than >those of microorganisms? If you let me know that parsnp does not deal with such large genomes, I >could save time and efforts to run parsnp on my datasets.

@abysslover Apologies for the terribly late reply to your great question. In fact it can handle larger genomes; I've aligned individual chromosomes across multiple closely-related mammalian genomes, and also used parsnp to identify ultraconserved elements (http://ultraconserved.org/) in eukaryote genomes. While parsnp is quite efficient w.r.t. cpu time for large sequences/genomes, memory requirement/usage will increase significantly. For large genome analysis, the reference can be partitioned into smaller chunks (I've used -P 10000000 for hg chr1), which will reduce the memory requirement while increasing the runtime. 

>Although the Genomes folder contains 3 genome assemblies, parsnp does not recognize them.

@plasmid02 , @AnitaVoigt, could you please provide a listing of the output files (or simply a list of fasta files sizes) in your genome directory, in addition to the size of the reference? 

>Did you find a solution yet?

Aside from just checking for proper fasta formatting & non-zero sequence length, there is a length filter; genomes must be within +/- 30% (bp) of the reference. I suspect for @abysslover , this is exactly what is happening. A single chromosome is provided as reference and assemblies are provided in the genome dir. For the others, hard to say without inspecting the output dir.

>I would be very happy to get a hint to solve the problem

If this is indeed what is happening, two improvements should be applied to the code to solve the problem:

1.  A more descriptive error message should be added to the output, 
2. The size diff cutoff should be an explicit parameter. 

I'll make sure to address both of these items in the next release. In the interim, if confirmed to be due to the size cutoff, I can post a pre-release binary should allow you to bypass this issue.

-Todd

**Comment by plasmid02** [comment]
I think the problem was caused by something wrong with the formatting of
one of the fasta files - been running with 3 genomes and it works fine.
The fixes Todd mentions above would be very useful.

**Comment by AnitaVoigt** [comment]
Dear Todd, dear Tim,

thank you for your replys and apologies for my late answer.

To me it appeared to not recognize my fasta files.
However, the next day when I run the same command again it worked fine and
I couldn't reproduce the error. I didn't change the format of my fasta
files. Maybe it helped that I restarted the computer/ terminal session (my
apologies, I am not a programming expert).

Kind regards,
Anita

**Comment by saadleeshehreen** [comment]
I need a parsnp.fasta file. There are parsnpAligner.ini parsnpAligner.log parsnp.ggr parsnp.tree parsnp.xmfa . How to generate the .fasta file? I tried to convert the .xmfa file to .fasta but that file is not compatible for another software named gubbins.

**Comment by Mor-Rubinsteinn** [comment]
I got that annoying error message 'Parsnp requires 2 or more genomes to run, exiting' when I was trying to use a compressed reference fasta file, but when I de-compressed it, it worked without a problem.
So that solved the problem for me.

**Comment by gizzlev** [comment]
> I need a parsnp.fasta file. There are parsnpAligner.ini parsnpAligner.log parsnp.ggr parsnp.tree parsnp.xmfa . How to generate the .fasta file? I tried to convert the .xmfa file to .fasta but that file is not compatible for another software named gubbins.

use Harvesttools to transform from .xmfa file to multi-fasta.

**Comment by emmannaemeka** [comment]
Hi,
I have a similar problem. I am working with a bacteria genome. My file structure looks like this

 emmannaemeka@Nnaemekas-MacBook-Pro parsnp % ls
genomes	ref

emmannaemeka@Nnaemekas-MacBook-Pro genomes % ls
22-120336_S17_1.fasta	22-120344_S20.fasta	222-120333_S16_1.fasta
22-120340_S18_1.fasta	22-120346_S21_1.fasta
22-120342_S19_1.fasta	22-120347_S22_1.fasta

 emmannaemeka@Nnaemekas-MacBook-Pro ref % ls
JALPLR01.1.gbk		JALPLR01.1.gbk.cat	JALPLR01.1.gbk.fna

However when I ran

/Users/emmannaemeka/Documents/bioiformatics_program/Harvest-OSX64-v1.1.2/parsnp -g /Users/emmannaemeka/Documents/benson/phy/parsnp/ref/JALPLR01.1.gbk  -d /Users/emmannaemeka/Documents/benson/phy/parsnp/genomes -C 1000 -c

It returned with this

|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
******************************************************************************************
SETTINGS:
|-refgenome:	/Users/emmannaemeka/Documents/benson/phy/parsnp/ref/JALPLR01.1.gbk.fna
|-aligner:	libMUSCLE
|-seqdir:	/Users/emmannaemeka/Documents/benson/phy/parsnp/genomes
|-outdir:	/Users/emmannaemeka/Documents/benson/phy/parsnp/P_2023_01_22_011236062278
|-OS:		Darwin
|-threads:	32
******************************************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from /Users/emmannaemeka/Documents/benson/phy/parsnp/genomes..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) /Users/emmannaemeka/Documents/benson/phy/parsnp/ref/JALPLR01.1.gbk..
  |->[OK]
Parsnp requires 2 or more genomes to run, exiting
[] /Users/emmannaemeka/Documents/benson/phy/parsnp/ref/JALPLR01.1.gbk.fna


Does anyone have a solution?

**Comment by bkille** [comment]
Hi @emmannaemeka! 

Thanks for using Parsnp and opening an issue. It looks like you're using v1.2, which is no long supported. You can find the current version of parsnp, v1.7.4, on [Bioconda](https://bioconda.github.io).
 
Once you install conda and set up the channels as described in the bioconda link above, you can run the following command to install parsnp 

```
conda install parsnp 
```

Please note that you'll need to be running Python 3, not Python 2.

**Comment by emmannaemeka** [comment]
Thanks for your reply. I updated my file and got this result

 *INFO* - |--Parsnp 1.7.4--|


15:42:02 - *ERROR* -
/Users/emmannaemeka/Documents/benson/phy/parsnp/genomes/.DS_Store is an
invalid sequence file!

Traceback (most recent call last):

  File "/Users/emmannaemeka/mambaforge/bin/parsnp", line 642, in <module>

    for record in records:

NameError: name 'records' is not defined


How do I solve this?


Nnaemeka Emmanuel Nnadi,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:

https://orcid.org/0000-0002-8424-4859

 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by bkille** [comment]
Can you provide the command you are using to run Parsnp? It also looks like there is a rogue `.DS_store` file in your genome directory.
