### ISSUE TITLE
Parsnp ignores three genomes

### ISSUE THREAD

**Issue by gsong1205** [marbl/parsnp#21]
Hi,

My reference is a chromosome and genome fold contains 8 assemblies. But when I run parsnp, it ignores three assemblies.
I checked the format of fasta files and they are correct.  All assemblies are within +-30% of the reference.
No zero length sequence.
I want to know why it happened.

Thanks!

**Comment by treangen** [comment]
hi,

could you please paste the command you are running? also, please provide the version of parsnp you are using. and roughly speaking, how similar is the reference genome to the 8 assemblies in the genomes folder?

**Comment by gsong1205** [comment]
I am not sure about the similarity.
parsnp version is v1.1.2
command: parsnp -r /home/p2012-123/WMC/Genomes/KpneumoniaeMGH78578/chromosome.fasta -d /home/biodatashare/PRNA-BioInterns/data/KP_Reference/KP_PacBio -o /home/biodatashare/PRNA-BioInterns/GeSong/tasks/harvest/testresult

**Comment by treangen** [comment]
Thanks for sending. I'd first try adding '-c' to the command to force include all of your genomes in the KP_PacBio directory (instead of recruitment, which is the default behavior).
