### ISSUE TITLE
issue with gbk file

### ISSUE THREAD

**Issue by jfmariet** [marbl/parsnp#22]
Hello, I'm trying to assess parsnp as a tool to work with Listeria genomes, but I am facing this issue

|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
ERROR: Genbank file ./media/ANALYSE/jmariet/tools/parsnp/Parsnp-Linux64-v1.2/data/tuto/ref/Lm_CC9_SLCC2479.gbk not found

I tried other answers proposed for former issues but this doesn't work.

Please could you help me to figure out what's going wrong?

regards

JF

**Comment by bkille** [comment]
It would help if you provided the command you used as well. However, there were number of genbank parsing issues that have been resolved in version 1.5
