### ISSUE TITLE
parsnp.vcf versus parsnp.snps

### ISSUE THREAD

**Issue by gotero** [marbl/parsnp#25]
According to the docs, parsnp.vcf is used to infer the phylogenetic tree. If so, then why does it contain the snps I want to filter out near recombination sites (-x option)? If REC and LCB snps are present in parsnp.vcf, how is parsnp.snps created?

**Comment by bkille** [comment]
Hi,

The `parsnp.snps.mblocks` file is creating with harvest-tools, and filters out any non `PASS` records in the VCF.
