### ISSUE TITLE
MUM distance matrix?

### ISSUE THREAD

**Issue by gotero** [marbl/parsnp#26]
Is it possible to create a matrix of all pairwise MUM distances between a set of genomes with parsnp? I tried inserting the -M option in my usual parsnp command : "parsnp -g <ref> -d <input dir> -p 8 -x -c -M -o <output dir>", but got this error: 
Traceback (most recent call last):
  File "<string>", line 876, in <module>
AttributeError: 'str' object has no attribute 'close'

**Comment by bkille** [comment]
The `-M` flag no longer causes this error, but I don't believe you'll be able to get all pairwise distances from this.
