### ISSUE TITLE
results: vcf file missing?   

### ISSUE THREAD

**Issue by karinlag** [marbl/parsnp#28]
Hi!

I just downloaded parsnp (for linux), and ran the mers example. However, I do not get a vcf file as an output file:

karinlag@bl8vbox[parsnp_test] ../../bin/Parsnp-Linux64-v1.2/parsnp -g ./ref/EMC_2012.gbk -d ./mers49 -c                                                                [10:52AM]
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
*************************************************************************
SETTINGS:
|-refgenome:	./ref/EMC_2012.gbk.fna
|-aligner:	libMUSCLE
|-seqdir:	./mers49
|-outdir:	/home/karinlag/tmp/parsnp_test/P_2017_02_08_105223126989
|-OS:		Linux
|-threads:	32
*************************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from ./mers49..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ./ref/EMC_2012.gbk..
  |->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
  |->[OK]
-->Running PhiPack on LCBs to detect recombination..
  |->[SKIP]
-->Reconstructing core genome phylogeny..
  |->[OK]
-->Creating Gingr input file..
  |->[OK]
-->Calculating wall clock time.. 
  |->Aligned 49 genomes in 0.82 seconds

<<Parsnp finished! All output available in /home/karinlag/tmp/parsnp_test/P_2017_02_08_105223126989>>

Validating output directory contents...
	1)parsnp.tree:		newick format tree 			[OK]
	2)parsnp.ggr:		harvest input file for gingr (GUI) 	[OK]
	3)parsnp.xmfa:		XMFA formatted multi-alignment 		[OK]

karinlag@bl8vbox[parsnp_test]

Is there something I should be doing that I have forgotten?

Karin

**Comment by aphillippy** [comment]
Hi Karin,
Check for the `harvest-tools` utility which can convert the compressed .ggr alignment file into VCF:
http://harvest.readthedocs.io/en/latest/content/harvest/quickstart.html

Best,
-Adam
