### ISSUE TITLE
Sequence headers in .xmfa

### ISSUE THREAD

**Issue by snayfach** [marbl/parsnp#31]
Does anyone know how to interpret the sequence headers in the .xmfa file?

For example, take the following:
`>28:462049-462515 - cluster8 s134:p5601`

I understand that "28" indicates the genome, "462049-462515" the coordinates, "-" the strand, and "cluster8" the LCB. But what about "s134:p5601"? What does this indicate?

I already read about the format here and couldn't find the answer:
http://darlinglab.org/mauve/user-guide/files.html

Thanks!

**Comment by AlexWanghaoming** [comment]
Is there an answer for this question?

**Comment by bkille** [comment]
Ahh yes, sorry. It is answered in #38
