### ISSUE TITLE
ERROR: ref genome sequence * seems to aligned! remove and restart 

### ISSUE THREAD

**Issue by ingotron** [marbl/parsnp#33]
Hello there,

I'm hoping to use parsnp to find SNPs in a small set of SAGs (Single Amplified Genomes). I've got six sets of contigs sequenced and assembled from single bacterial cells in the folder NBK19/. Since there are no references for this species, I tried to run the autorecruiting option first, and then the FASTA reference option selecting a random genome from the folder. My commands looked like the following (executed within the directory:

`$ parsnp -q AG-470-J09_contigs.fasta -d . -p 4`
`$ parsnp -r ! -d . -p 4`

In both cases, parsnp reads the available FASTA files and then dies:

`-->Reading Genbank file(s) for reference (.gbk) ..`
 ` |->[WARNING]: no genbank file provided for reference annotations, skipping..`
`ERROR: ref genome sequence AG-470-J09_contigs.fasta seems to aligned! remove and restart`

The actual reference sequence varies when I'm running the random reference FASTA option, but the gist of the error is always "seems to aligned!" Any idea what this is about?

In case it's relevant, I'm running this on OSX.

Thanks,
/Ingo Ohlsson

**Comment by snayfach** [comment]
I get the same error on Unix using parsnp v1.2. I only get the error when certain genomes are specified as the representative (-r option). I don't see any difference between the genomes that cause this error versus those that don't. I'm using draft genomes from isolates, all belonging to the same species.

It's not clear to me what the error message means. I'm trying to incorporate parsnp into a pipeline, but this unpredictable error is problematic.

Any help would be appreciated.

Thanks,
Stephen

**Comment by snayfach** [comment]
Others have noted that this error is caused by dashes in sequence identifiers: https://github.com/marbl/harvest/issues/19

**Comment by advaitb** [comment]
Thanks @Fu-Yilei for bringing the problem to my attention. Headers can now have "-" in them.

**Comment by romerojazmin** [comment]
> Thanks @Fu-Yilei for bringing the problem to my attention. Headers can now have "-" in them.
The issue is still persisting.

**Comment by bkille** [comment]
Hi @romerojazmin!

What version of Parsnp are you using? I am able to run parsnp on sequences which have `-` in the header with version 2.0.2 as well as version 1.7.4.

**Comment by romerojazmin** [comment]
Thank you.
Yes, I realized yesterday. I was running an old version (1.2).


________________________________

**Comment by romerojazmin** [comment]
Also, how do you install later versions from parsnp?

________________________________

**Comment by bkille** [comment]
Your best bet is to use `conda`. The instructions are [here](https://github.com/marbl/parsnp?tab=readme-ov-file#from-conda). Be sure to follow the hyperlinks to set up the bioconda channel, if you haven't already. 

Let me know if you run into any issues!
