### ISSUE TITLE
Mapping coordinates of the MAF back to the reference

### ISSUE THREAD

**Issue by plasmid02** [marbl/parsnp#38]
Anyone know if someone has solved how to map coordinates from the multi-alignment file output back to the original coordinate son the reference genbank file?

If it hasn't been done, I make have a a try at it.

**Comment by bkille** [comment]
The header for each record is the following

```
[fileidx]:[concat_start]-[concat_end] [strand] cluster[x] s[contig_idx]:p[contig_pos]
```

The `concat_start` and `concat_end` values are internal to parsnp. The sequence for this record can be found in the file at index `fileidx` (these are declared at the top of the xmfa) on the `contig_idx`th contig starting at position `contig_pos`.
