### ISSUE TITLE
Parsnp requires 2 or more genomes to run, exiting

### ISSUE THREAD

**Issue by Anuravi123** [marbl/parsnp#40]
Hello,

I am using a fasta file as a reference and 2 denovo assembled contig files as my query. I know the query files have the reference with some SNPs. This is the command I am using

parsnp -q ./GCF_001077715.1_ASM107771v1_genomic.fna -d ./concat_seq/ -o test/ -p 12

My error log looks like this:
-->Reading Genome (asm, fasta) files from ./concat_seq/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
Parsnp requires 2 or more genomes to run, exiting
[]
I am not sure where the problem lies and any input on this will be of great help!

Thank you!

**Comment by gotero** [comment]
You have to use the -r option for your reference genome, like so:
> 
> parsnp -r ./GCF_001077715.1_ASM107771v1_genomic.fna -d ./concat_seq/ -o test/ -p 12
> 
> 


Glen Otero Ph.D.
Linux Prophet
619.917.1772

**Comment by Anuravi123** [comment]
Thanks for your reply. I was trying a number of options including -r and it didnt work with it either.

Anu

**Comment by shlomobl** [comment]
Hi,
I had the same issue. I was using a gbf file for reference that was created with Prokka with -g flag and got:
_<<Parsnp started>>
-->Reading Genome (asm, fasta) files from ./..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) PmB1.gbf..
  |->[OK]
Parsnp requires 2 or more genomes to run, exiting
PmB1.gbf.fna_
Even though it says in the site that non-NCBI (i.e. without GI) would work, just would not show annotations in the browser.
I changed the ref. genome to fasta and used the -r flag and it worked OK.
Now that GI are gone and people often analyze their genomes before NCBI submission (which today would not generate GI anyway) it would be cool to have an upgrade on this.

**Comment by iferres** [comment]
Same issue here. I think it's related to the " +- 30% " requirement referenced by @sconlan here: https://github.com/marbl/parsnp/issues/40#issuecomment-387157021
It would be nice no have the option to disable this restriction.

**Comment by advaitb** [comment]
We will have a (mini) release soon and add a parameter to ask Parsnp explicitly circumvent the length cutoff.
