### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Derreckadam** [marbl/parsnp#42]
I notitced that this was an issue previously, but it was the result of too many arguments (-r and -g) I am getting the same error, but I'm only using -g. I've tried running this on linux, and High Sierra. and both give me the error message, not sure what I'm doing wrong.  Here I am using the tutorial data and getting the error message. 

Thanks,
Derreck 

~/Parsnp/Parsnp-Linux64-v1.2$ ./parsnp -g ../ref/EMC_2012.gbk -d ../mers49/ -c
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
******************************************************************************************************************
SETTINGS:
|-refgenome:	../ref/EMC_2012.gbk.fna
|-aligner:	libMUSCLE
|-seqdir:	../mers49/
|-outdir:	/bigdata/stajichlab/shared/projects/Serratia/Parsnp/Parsnp-Linux64-v1.2/P_2018_03_14_104433759406
|-OS:		Linux
|-threads:	32
******************************************************************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from ../mers49/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ../ref/EMC_2012.gbk..
  |->[OK]
Traceback (most recent call last):
  File "<string>", line 656, in <module>
IndexError: string index out of range

**Comment by sambrano** [comment]
Hi @Derreckadam, 

Did you sort it out? I'm trying to run parsnp with 203 genomes and I'm receiving the same message. I tried with less genomes and it worked fine. 

I'm starting to think it does not support this amount of data.

Thanks

Gustavo Sambrano

**Comment by bkille** [comment]
This was an issue w/ the example .gbk file which we've fixed. Parsnp should be totally fine handling that number of genomes. The error was simply due to parsing.
