### ISSUE TITLE
Order of arguments seems to matter

### ISSUE THREAD

**Issue by mjsull** [marbl/parsnp#44]
Hi,

It seems that parsnp requires it's arguments to be in a specific order. For example, if I use the -P argument before -o it writes the output to P_* directory instead of the directory specified by -o. It runs fine if I include the -P argument at the end.

-Mitchell

**Comment by bkille** [comment]
I'm not sure what would cause this, but it is fixed on the `pythonificate` branch by using argparse. The branch will be merged soon. Will close issue then.
