### ISSUE TITLE
Work with 1000 genomes

### ISSUE THREAD

**Issue by OrsonMM** [marbl/parsnp#48]
Dear team parsnp

I have a directory with **1320 assemblies genomes**. I run the command

parsnp -g ../../DB_all/genome_reference_VP/CP007004.gbk,../../DB_all/genome_reference_VP/CP007005.gbk -d ../../Data/all_v_p_for_parsnp/ -p 6

**It works well but only aligment 73 genomes.**

######################

For detailed documentation please see --> http://harvest.readthedocs.org/en/latest

SETTINGS:
|-refgenome: ../../DB_all/genome_reference_VP/CP007004.gbk.fna
|-aligner: libMUSCLE
|-seqdir: ../../Data/all_v_p_for_parsnp/
|-outdir: /home/ubuntu/Results/all_1327_parsnp/P_2018_06_11_185050006955
|-OS: Linux
|-threads: 6

<>

-->Reading Genome (asm, fasta) files from ../../Data/all_v_p_for_parsnp/..
|->[OK]
-->Reading Genbank file(s) for reference (.gbk) ../../DB_all/genome_reference_VP/CP007004.gbk,../../DB_all/genome_reference_VP/CP007005.gbk..
|->[OK]
-->Calculating MUMi..
|->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..

|->[OK]
-->Running PhiPack on LCBs to detect recombination..
|->[SKIP]
-->Reconstructing core genome phylogeny..
|->[OK]
-->Creating Gingr input file..
|->[OK]
-->Calculating wall clock time..
|->Aligned 73 genomes in 1.00 hours

<<Parsnp finished! All output available in /home/ubuntu/Results/all_1327_parsnp/P_2018_06_11_185050006955>>

Validating output directory contents...
1)parsnp.tree: newick format tree [OK]
2)parsnp.ggr: harvest input file for gingr (GUI) [OK]
3)parsnp.xmfa: XMFA formatted multi-alignment [OK]

**Comment by huizhen2014** [comment]
I had encountered the same issue. When I used my Mac to run the program with 22 contigs, it could not output all the contigs' result, and the number of contigs used by the parsnp were different along the thread I used.

**Comment by advaitb** [comment]
Parsnp onlyworks with genomes that filter past the MUMi distance and length thresholds.If you want to force Parsnp to use all genomes/sequences then please run parsnp with the  _-c_ flag.
