### ISSUE TITLE
Parsnp error

### ISSUE THREAD

**Issue by sambrano** [marbl/parsnp#49]
Hello, I recently installed the Parsnp tool on my Ubuntu 18.04 LTS and when I tried to run the tool I ended up with the following error. 

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from /home/preventiva/Desktop/Teste..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Calculating MUMi..
  |->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
  |->[OK]
-->Running PhiPack on LCBs to detect recombination..
  |->[SKIP]
-->Reconstructing core genome phylogeny..
**ERROR**
The following command failed:
>>fasttree -nt -quote -gamma -slow -boot 100 /home/preventiva/P_2018_06_14_205550206988/parsnp.snps.mblocks > /home/preventiva/P_2018_06_14_205550206988/parsnp.tree
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**
Am I doing something wrong? I've already checked the fasttree software and it is correctly installed.

Thank you for your help.
Gustavo Sambrano

**Comment by fchiesa** [comment]
Hi Gustavo, I see you didn't get much support. Did you solve the issue by yourself, by any chance? I have exactly the same problem. 

Francesco Chiesa

**Comment by sambrano** [comment]
Hi Francesco, unfortunately I couldn't sort it out. Did you try uninstalling and installing the software again?
Gustavo Sambrano

**Comment by tillea** [comment]
On Mon, Jan 14, 2019 at 08:46:57AM -0800, sambrano wrote:
> Hi Francesco, unfortunately I couldn't sort it out. Did you try uninstalling and installing the software again?
I'm maintaining those packages in Debian (same code is automatically propagated to Ubuntu as derivative).  I can't imagine that uninstalling and reinstalling the package would lead to any change.  To track the issue down could we try the following: "Run a simple test suite featuring the error, put all input and output data in an archive and upload it here including the axact command line that leads to the error."
In turn Gustavo does the very same with his setup (mentioning all versions of those programs) and uploads the files in another archive.  Than we can compare at what point the failure happens and in how far the results are deriving from what is to be expected.
Kind regards, Andreas.

**Comment by sambrano** [comment]
Hi Andreas, thank you for your reply. I'm using parsnp version 1.2. I have to say that I used the software before and it worked very well but now in my new computer it shows the error below: 

preventiva@preventiva-System-Product-Name:~$ parsnp -r /home/preventiva/Documents/Sambrano/Doutorado/Spyo_fasta/fasta/Blood.fasta -d /home/preventiva/Documents/Sambrano/Doutorado/Spyo_fasta/fasta -p 8
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
***********************************************************
SETTINGS:
|-refgenome:	/home/preventiva/Documents/Sambrano/Doutorado/Spyo_fasta/fasta/Blood.fasta
|-aligner:	libMUSCLE
|-seqdir:	/home/preventiva/Documents/Sambrano/Doutorado/Spyo_fasta/fasta
|-outdir:	/home/preventiva/P_2019_01_18_145308098851
|-OS:		Linux
|-threads:	8
***********************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from /home/preventiva/Documents/Sambrano/Doutorado/Spyo_fasta/fasta..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Calculating MUMi..
  |->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
  |->[OK]
-->Running PhiPack on LCBs to detect recombination..
  |->[SKIP]
-->Reconstructing core genome phylogeny..
**ERROR**
The following command failed:
>>fasttree -nt -quote -gamma -slow -boot 100 /home/preventiva/P_2019_01_18_145308098851/parsnp.snps.mblocks > /home/preventiva/P_2019_01_18_145308098851/parsnp.tree
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

I've attached the fasta files I used to run this test. 
Anything you need please don't hesitate to ask.

Thank you very much

[fasta.zip](https://github.com/marbl/parsnp/files/2773803/fasta.zip)

**Comment by nandrews56** [comment]
Hi,

Was this issue ever resolved? I'm facing the very same problem. I've installed Parsnp via the Debian distribution, but am getting an error when trying to run the tutorials. As posted by the previous users, the package is launching fine and running the initial routines apparently without issue, but is then posting an error when Reconstructing core genome phylogeny -

**ERROR**
The following command failed:
>>fasttree -nt -quote – gamma -slow -boot 100 /home/nick/(folder)/parsnp.snps.mblocks > /home/nick/(folder)/parsnp.tree
Please veryify input data and restart Parsnp. If the problem persists please contact the Parnsp development Team.
**ERROR**

I take it that there's no input file available for FastTree, as there is no file named parsnp.snps.mblocks in the folder that's been created (sorry, I didn't note the name of that folder). Could anyone help?

Many thanks,

Nick Andrews

**Comment by sambrano** [comment]
I downloaded the fast tree from its website and put it on the same folder that parsnp had been installed and it worked. I suggest you to do the same.

Thanks

Gustavo Sambrano

**Comment by nandrews56** [comment]
Many thanks Gustavo,

I'm just getting back to this now and will give this a try.

Thanks,

Nick

**Comment by bkille** [comment]
Hello @nandrews56, @sambrano and @fchiesa , I'm the new maintainer of Parsnp so I'll be taking a look at these issues. 

For those of you experiencing the following error:

```
ERROR
The following command failed:

fasttree -nt -quote – gamma -slow -boot 100 [output_directory]/parsnp.snps.mblocks > [output_directory]/parsnp.tree
Please verify input data and restart Parsnp. If the problem persists please contact the Parnsp development Team.
ERROR
```

Please try running the failed command and attach the output here on this issue. It will help me determine whether this is an issue with one of the dependent binaries or an issue with the Parsnp code itself. 

In the meantime, you can try building Parsnp from source using the `build_parsnp_*.sh` scripts, as there have been a number of small bugs that have been fixed since the last debian and conda shipments. Once I finish cleaning out all of the small bugs and adding some small features, I will update the packaged versions of Parsnp.

**Comment by bkille** [comment]
@sambrano, given your input data, I was able to run parsnp using your command and obtained the following tree:
('VS.fasta':0.52565,'Skin.fasta':0.58030,('Blood.fasta.ref':0.36583,'oropharynx.fasta':0.34432)0.840:0.00988);

**Comment by nandrews56** [comment]
Forgive me bkille, I'm a Linux newbie, so not fully sure of the ask!
I downloaded and extracted the 49 MERS Coronavirus tutorial files to my Downloads folder (getting a ref folder and a mers49 folder). In Terminal, I then navigated to this folder and entered the command:
parsnp -g ref/EMC_2012.gbk -d mers49 -c

with the following text resulting:
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
***************************************************************
SETTINGS:
|-refgenome:	ref/EMC_2012.gbk.fna
|-aligner:	libMUSCLE
|-seqdir:	mers49
|-outdir:	/home/nick/Downloads/P_2020_02_11_211036538489
|-OS:		Linux
|-threads:	32
***************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from mers49..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ref/EMC_2012.gbk..
  |->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
  |->[OK]
-->Running PhiPack on LCBs to detect recombination..
  |->[SKIP]
-->Reconstructing core genome phylogeny..
**ERROR**
The following command failed:
>>fasttree -nt -quote -gamma -slow -boot 100 /home/nick/Downloads/P_2020_02_11_211036538489/parsnp.snps.mblocks > /home/nick/Downloads/P_2020_02_11_211036538489/parsnp.tree
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

This is the output folder (I hope it's copied in OK)  ....

x-special/nautilus-clipboard
copy
file:///home/nick/Downloads/P_2020_02_11_211036538489

There's also an empty 'allmums.out' file in the Downloads folder.

**Comment by nandrews56** [comment]
I think I managed to attach the output folder ...

[outputs.zip](https://github.com/marbl/parsnp/files/4188511/outputs.zip)

**Comment by sambrano** [comment]
> @sambrano, given your input data, I was able to run parsnp using your command and obtained the following tree:
> ('VS.fasta':0.52565,'Skin.fasta':0.58030,('Blood.fasta.ref':0.36583,'oropharynx.fasta':0.34432)0.840:0.00988);

Dear @bkille Thank you very much for your help. I was able to sort it out few months ago when I downloaded the fast tree separately. Now parnsp is working perfectly. 

Thanks for your attention.

Gustavo Sambrano

**Comment by bkille** [comment]
@sambrano Okay great! So an issue w/ the Fasttree binary then. I'll have to look into why that didn't work on Ubuntu 18.04...

**Comment by nandrews56** [comment]
Hi Bryce,

I'm afraid I haven't had much success. I confirmed that FastTree is working (with just the -nt -gtr options) by creating a simple tree in my home directory. I downloaded FastTree separately and placed into the /usr/share/parsnp folder (alongside the Parsnp python script), and made sure that it would run by typing the command chmod 755 FastTree in that folder. Parsnp still returned the same error. I then manually removed the 3 fasttree links from /usr/bin (fasttree, FastTree and fasttreeMP), thinking that Parsnp might still be calling these, but without success. I also created a symbolic link to /usr/share/parsnp/FastTree in the /usr/bin folder, but no luck.

For now I have removed Parsnp and it's dependencies while I think about downloading and building from source. Is this reasonably straightforward?

Thanks,

Nick

**Comment by bkille** [comment]
@nandrews56  Looking at your output folder, it would appear that in your case the `parsnp.snps.mblocks` is not being created, so FastTree isn't even able to run in the first place. This is an issue w/ the [harvest tools](https://github.com/marbl/harvest-tools) binary. There is a bug with processing `.gbk` files. I have fixed this in the current version of Parsnp, so you  will be able to use `.gbk` files if you install Parsnp from the source. Otherwise you will have to wait until the next update is released (which should be soon) 

I apologize for the delay!

-Bryce

**Comment by nandrews56** [comment]
Many thanks Bryce,
I'm just in the process of installing directly, so hopefully this will resolve the problem. I appreciate the help.
Nick

**Comment by nandrews56** [comment]
Hi Bryce,
Have just completed the installation (downloading the tarball from github via wget) and all is good!
Thanks again, Nick
