### ISSUE TITLE
Random reference gets ".srt" added to its label

### ISSUE THREAD

**Issue by tseemann** [marbl/parsnp#5]
Two file "1.fa" and "2.fa" in dir 'fasta'.

Run "parsnp -r '!' -d  fasta -o out" 

Look at "out/parsnp.tree"  ('2.fa.srt':0.0,'1.fa':0.0);

I assume the .srt suffix on the label refers to the one that was chosen as the reference?

Should it be there?

**Comment by treangen** [comment]
```Should it be there?````

Yes, but please allow me to clarify. The .srt file indeed indicates the selected reference genome, and is sorted by replicon size (from largest to smallest, hence the .srt suffix). While it was initially added to address a minor bug in harvesttools, we decided to leave it in for consistency (first replicon in reference will always be the largest one); I will be sure to better describe this in the documentation.

**Comment by tseemann** [comment]
Thanks Todd.
