### ISSUE TITLE
Parsnp 1.2 prints v1.0.1 with parsnp -h

### ISSUE THREAD

**Issue by tseemann** [marbl/parsnp#52]
```
parsnp -v
Parsnp v1.0.1

./src/parsnp.cpp:    string pversion = "v1.0.1";
```

**Comment by tseemann** [comment]
@Fu-Yilei This is still a bug?
`https://github.com/marbl/parsnp/blob/63bea137e2726c860133f0b97da688dab3c1b92b/src/parsnp.cpp#L2754`

**Comment by Fu-Yilei** [comment]
Also fixed in my branch, will be merged into master shortly, thanks

**Comment by tseemann** [comment]
Thanks
