### ISSUE TITLE
On an E. coli project: "Parsnp requires 2 or more genomes to run, exiting"

### ISSUE THREAD

**Issue by lskatz** [marbl/parsnp#54]
Hi, I have a genome that was annotated with ISFinder and with PhageFinder, and I have a directory of fasta files.  This command ends in an error and I cannot figure out why.  Could I ask for your help?"

The exact command:
`parsnp -g 2011EL1370sc2.mobileElements.gbk -d asm -p 12 -o parsnp4.LK -c -C 1000`

I basically combined the features and the sequence using bioperl

```
perl -MData::Dumper -MBio::Perl -MBio::FeatureIO -e '$bedin=Bio::FeatureIO->new(-file=>"annotations.gff");$seqout=Bio::SeqIO->new(-file=>">out.gbk"); $seqin=Bio::SeqIO->new(-file=>"2011EL1370sc2.fasta"); while($seq=$seqin->next_seq){$seq{$seq->id}=$seq;}; while($feat=$bedin->next_feature){$i++; $seq{$feat->seq_id}->add_SeqFeature($feat);} for(values(%seq)){$seqout->write_seq($_);}'
```

The beginning of the genbank file looks like this:

```
LOCUS       contig001_2011EL1370sc2      4785142 bp    dna     linear   UNK
ACCESSION   unknown
FEATURES             Location/Qualifiers
     CDS             4131758..4135345
                     /source="."
                     /seq_id="contig001_2011EL1370sc2"
                     /phase="."
                     /score="."
                     /type="CDS"
                     /Name="ISL3"
     CDS             640969..638420
                     /source="."
                     /seq_id="contig001_2011EL1370sc2"
                     /phase="."
                     /score="."
                     /type="CDS"
                     /Name="ISL3"
```

```
[gzu2@monolith3 tmp]$ parsnp -g 2011EL1370sc2.mobileElements.gbk -d asm -p 12 -o parsnp4.LK -c -C 1000
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
***************************
SETTINGS:
|-refgenome:    2011EL1370sc2.mobileElements.gbk.fna
|-aligner:      libMUSCLE
|-seqdir:       asm
|-outdir:       parsnp4.LK
|-OS:           Linux
|-threads:      12
***************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from asm..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) 2011EL1370sc2.mobileElements.gbk..
  |->[OK]
Parsnp requires 2 or more genomes to run, exiting
[] 2011EL1370sc2.mobileElements.gbk.fna
```

**Comment by lskatz** [comment]
also: I know that if I use `-r` with the original fasta file instead of `-g` with the genbank file, then it works.  So I know that the directory of assemblies and the reference fasta file are good.

**Comment by treangen** [comment]
Hi Lee, 

thanks for posting -- per your findings (-r vs -g), sure looks like an issue parsing the genbank file, but I"ll need to dig further into this and get back to you. My initial guess is that it is not parsing out the fasta sequence properly and thus fails to create a reference genome. Can you verify that the genome sequence is available at the end of the GBK file ? A tail of the last few lines would suffice.

**Comment by lskatz** [comment]
Thank you!!

[out.gbk.txt](https://github.com/marbl/parsnp/files/2376290/out.gbk.txt)

**Comment by treangen** [comment]
Thanks! Can you confirm 2011EL1370sc2.mobileElements.gbk.fna is nonzero/properly formatted fasta file?

**Comment by lskatz** [comment]
Yes I believe it is

**Comment by lskatz** [comment]
[2011EL1370sc2.txt](https://github.com/marbl/parsnp/files/2393917/2011EL1370sc2.txt)

**Comment by bkille** [comment]
@lskatz Hi there! I'm the new maintainer of Parsnp. Sorry for the delayed reply, but I figure it is better late than never!  The new release of Parsnp has fixed this genbank parsing issue. Please let me know if it persists for you

**Comment by lskatz** [comment]
All right!  Thank you!  I cannot test at this time and so I will close and will reopen it if it persists.
