### ISSUE TITLE
configure.ac has wrong parsnp version in it

### ISSUE THREAD

**Issue by tseemann** [marbl/parsnp#55]
```
% head configure.ac

AC_INIT(parsnp,1.0)
AM_INIT_AUTOMAKE(parsnp,1.0)
AC_PROG_CC(gcc)
```

**Comment by tseemann** [comment]
@Fu-Yilei & @treangen  -- why did you close this issue?
the bug still exists: https://github.com/marbl/parsnp/blob/63bea137e2726c860133f0b97da688dab3c1b92b/configure.ac

**Comment by Fu-Yilei** [comment]
Sorry I fixed it in my branch, will merge into master shortly. Thanks for your reminder

**Comment by tseemann** [comment]
Thank you
