### ISSUE TITLE
Run error parsnpAligner.ini

### ISSUE THREAD

**Issue by innovate-invent** [marbl/parsnp#59]
Installing ParSNP from conda doesn't seem to work.
I get the following error running on some basic Pseudomonas genomes taken from NCBI.
```bash
parsnp -d /home/nolan/Data/Pseudomonas_Genomes -o /home/nolan/Results/ -r ! -c
...
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
**ERROR**
The following command failed:
>>/tmp/_MEItORVk1/parsnp /home/nolan/Downloads//parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**
```
This seems to be the same problem as #35 but I am creating a new issue as that one has not been addressed in several years.

**Comment by innovate-invent** [comment]
What is used to generate the parsnp binary in the release? It seems as if it is not unpacking the bin folder from itself.

**Comment by innovate-invent** [comment]
It appears these issues do not occur on a mac. In linux
building from source and running Parsnp.py with python2 seemed to get a bit further but returns the same error.

Manually running `/tmp/_MEItORVk1/parsnp /home/nolan/Downloads//parsnpAligner.ini` fails with:
```
*** ERROR ***  DistKmer4_6 requires nucleo alphabet

*** ERROR ***  MSA::GetLetter(3/4, 1/11)='T'/4294967295

*** ERROR ***  MSA::GetLetter(0/5, 4/12)='G'/4294967295
```

**Comment by innovate-invent** [comment]
It seems the problem is specific to my computer:
```bash
uname -a
Linux ASUS-N580GD 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux
```

Running ParSNP inside a Debian docker instance fails just the same, but if I run it in a KVM ubuntu image it doesn't fail. I can only speculate that KVM isn't forwarding some CPU feature that libMUSCLE fails to use.

**Comment by indexofire** [comment]
same error, same error. all arch, arch-related distro and docker in arch failed both package/conda and compiling installation . and runing parsnp was fine in ubuntu.

**Comment by bkille** [comment]
Ahh. I've also seen this issue. Has something to do with OpenMP. We have resolved this in our current builds, but depending on your build system you may still get this error. Please let me know.
