### ISSUE TITLE
tutorial fails

### ISSUE THREAD

**Issue by tbrown99** [marbl/parsnp#60]
I tried to run the tutorial from this web site:
https://harvest.readthedocs.io/en/latest/content/parsnp/tutorial.html,

using the command given on the same website: 
./parsnp -g ./ref/EMC_2012.gbk -d ./mers49 -c

I got this output:

tbrown@debian1:~/Kate/Harvest-Linux64-v1.1.2$ ./parsnp -g ./ref/EMC_2012.gbk -d ./mers49 -c
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
***********************************************************************************
SETTINGS:
|-refgenome:	./ref/EMC_2012.gbk.fna
|-aligner:	libMUSCLE
|-seqdir:	./mers49
|-outdir:	/home/tbrown/Kate/Harvest-Linux64-v1.1.2/P_2019_05_15_181215575876
|-OS:		Linux
|-threads:	32
***********************************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from ./mers49..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ./ref/EMC_2012.gbk..
  |->[OK]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
**ERROR**
The following command failed:
>>/tmp/_MEIaVjATQ/parsnp /home/tbrown/Kate/Harvest-Linux64-v1.1.2/P_2019_05_15_181215575876/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

I am running the software on a debian machine.

**Comment by bkille** [comment]
There was an issue with genbank parsing in version 1.2. I'm closing this as I believe it is fixed in 1.5
