### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [marbl/parsnp#63]
Hello,
the Debian Med team is maintaining parsnp for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we continue to maintain parsnp in official Debian (and that users of other modern distributions will have no problems to install parsnp on their systems) I'd recommend you port your code to Python3. The 2to3 tool might be of great help here.
Kind regards, Andreas.

**Comment by tillea** [comment]
I have createt a [patch](https://salsa.debian.org/med-team/parsnp/blob/master/debian/patches/2to3_new.patch) for the Python3 migration you might like to verify.  It would be extremely helpful if you could provide a test script or at least a documentation how to process the provided example data and to compare these with some expected output.  We could use this as Continuous Integration test to make sure the conversion was successful.
Kind regards, Andreas.

**Comment by tseemann** [comment]
@tillea can you make a PR for this repo instead?

**Comment by advaitb** [comment]
Ported to python 3, Thanks @tillea!

**Comment by tillea** [comment]
Great!  Could you please tag a release?

**Comment by tseemann** [comment]
https://github.com/marbl/parsnp/releases
wow - has it really been 4.5 years? time flies!

**Comment by advaitb** [comment]
@tillea we will have a (mini) release soon with minor bug fixes.

**Comment by tseemann** [comment]
You don't have to make an actual release. A tag is enough. it won't "stand out" like a release.
```
git tag v1.2.1
git push --tags
```

**Comment by tillea** [comment]
Hi,
On Wed, Nov 13, 2019 at 09:00:11PM +0000, Torsten Seemann wrote:
> git tag v1.2.1
Thanks a lot, that worked.
I noticed that you did not took over the chunk of our patch replacing

    seq_len.iteritems()

which is not available in Python3 any more.  So I kept the tiny patch

    https://salsa.debian.org/med-team/parsnp/blob/master/debian/patches/2to3_new.patch

for the Debian package (may be you can drop the enclosing iter() - that's what
2to3 created but it looks somehow superfluous).

BTW, it would be great to have some kind of test suite for parsnp.

Kind regards, Andreas.
