### ISSUE TITLE
How many bootstrap replicates are made for tree reconstruction with Parsnp?

### ISSUE THREAD

**Issue by Phytobacteriology-UPNA** [marbl/parsnp#67]
Hi! 
Thanks a lot for this wonderful software, which made my research so much easier!
I made a SNPs tree using Parsnp for a collection of bacteria, and I got a newick tree that was imported to Mega7 for manipulation. The tree comes with bootstrap support. We are in the process of publishing, and we were wondering how many bootstrap replicates are made by Parsnp. We could not find any way to control this parameter (not that it matters), nor information on the actual number.
I would greatly appreciate if you could let me know how many replicates are made.
Thanks very much!

**Comment by advaitb** [comment]
Hi @Phytobacteriology-UPNA,

Parsnp uses Fastree for ML-tree generation and uses and runs it with a  bootstrap value (-boot) of 100.
