### ISSUE TITLE
Please add --version flag

### ISSUE THREAD

**Issue by tseemann** [marbl/parsnp#7]
Ideally a simple ```--version``` flag to help make it easy to bundle into Galaxy and Homebrew.

    % parsnp --version
    parsnp 1.1

**Comment by treangen** [comment]
Hi Torsten, 

Thanks for pointing this out. As of v1.1, a version flag has been added to Parsnp and will print via -V (but not -v ). happy to swap to -v (or add --version) if easier for bundling etc, but -v is currently in use for verbose mode.

-Todd

**Comment by tseemann** [comment]
Oh thanks Todd!  "-V" is fine.

(I didn't notice because I had to revert to Harvest 1.0 as there is some bug in 1.1 for me which I will post as a separate issue soon)
