### ISSUE TITLE
libtinfo.so.5: error

### ISSUE THREAD

**Issue by Panzenhagen** [marbl/parsnp#72]
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
/bin/bash: /tmp/_MEIkrzLEE/libtinfo.so.5: no version information available (required by /bin/bash)
**ERROR**
The following command failed:
>>/tmp/_MEIkrzLEE/parsnp parsnp_out/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

**Comment by bkille** [comment]
This is an error due to out of date binaries from your installation source. They will be updated with the next release of parsnp in the near future. In the meantime, installing parsnp from source has worked for other users who run into this.

**Comment by bawee** [comment]
Hi Bryce, I'm also getting this libtinfo.so.5 issue when running the executable on Windows Substyem for Linux. Trying to install from source with the script `build_parsnp_linux.sh` installs parsnp version 1.0.1. How do specify the installation of version 1.2 from source? 

Thanks!

https://gist.github.com/bawee/e2176c84543d45ee49963fc1a0976639

**Comment by bkille** [comment]
Hi, 

We've updated the build process to hopefully remedy issues like these. Please try the latest release (1.5.0) and let me know if the issue persists
