### ISSUE TITLE
Cannot open reference file !

### ISSUE THREAD

**Issue by lanlan0210** [marbl/parsnp#73]
Hi~
I just installed parsnp and reported an error while running the program.  The genome I used is the example you used: 49 MERS Coronavirus.  The reported error is shown below:

Cannot open reference file !

Looking forward to your reply. Thank you very much

**Comment by bkille** [comment]
Hi, that example contained hidden MacOS files w/ the prefix `._`, you can delete them via `rm mers49/._*` or redownload the zip file (it has been updated)
