### ISSUE TITLE
Build binary release on older glibc?

### ISSUE THREAD

**Issue by tseemann** [marbl/parsnp#77]
Are you able to build the binary lease `Parsnp-Linux64-v1.5.0.tar.gz` on an older system so it works on more systems?

It doesn't work on RHEL 7.x etc

Centos 6 is a common choice here that people use.

```
./parsnp: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./parsnp)
./parsnp: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./parsnp)
./parsnp: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./parsnp)
./parsnp: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./parsnp)
./parsnp: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./parsnp)
```

**Comment by bkille** [comment]
@tseemann  Thanks for going through all of this so thoroughly! I've updated the binary package to work w/ older versions. Let me know if that still doesnt fix those dependencies.
