### ISSUE TITLE
IndexError 

### ISSUE THREAD

**Issue by andrewdhuang** [marbl/parsnp#8]
Hi!

I'm getting the following error when executing parsnp on my directory of assemblies. Glancing at the code, it seems like it might have something to do with the header in my assemblies. Any ideas?

## Header example:
\>contig_27 Flow:          1 Edge  (   1504526,    2275572) String Length:      11237 Coverage:          0

## Error:
>~/bin/Parsnp-Linux64-v1.2/parsnp -r ../../3050.fasta -d ../LargeContigs/ -v YES -p 12
>|--Parsnp v1.2--|
>For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
>*********************************************************************************************************************************************
>SETTINGS:
>|-refgenome:    ../../2013T3050-joined.fasta
>|-aligner:      libMUSCLE
>|-seqdir:       ../LargeContigs_Mike/
>|-outdir:       /LargeContigs_Mike/P_2015_05_05_171008977035
>|-OS:           Linux
>|-threads:      32
>*********************************************************************************************************************************************
>
><<Parsnp started>>
>
>-->Reading Genome (asm, fasta) files from ../LargeContigs/..
>  |->[OK]
>-->Reading Genbank file(s) for reference (.gbk) ..
>  |->[WARNING]: no genbank file provided for reference annotations, skipping..
>Traceback (most recent call last):
>  File "<string>", line 656, in <module>
>IndexError: string index out of range

**Comment by andrewdhuang** [comment]
My mistake. One of my assemblies was empty for some reason. Thanks anyways!

**Comment by treangen** [comment]
ok, glad you figured it out. clear error output for this formatting issue will be added to the upcoming release.
