### ISSUE TITLE
Error:ref seq seems to be aligned 

### ISSUE THREAD

**Issue by tadediran** [marbl/parsnp#84]
Hi,

I am trying to align a sequence I pulled from Genbank with two draft isolate genomes that are in a directory. Unfortunately, when I run this, I get the error ref seq seems to be aligned. Syntax below:

/Users/tadediran/Desktop/Parsnp-OSX64-v1.2/parsnp -r /Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3_all/usa400_annotation.fasta  -d /Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3_all/All_pair_data/

Any help would be appreciated

**Comment by bkille** [comment]
@tadediran can you please attach the full output of parsnp? And can you confirm that there are no gaps (`-`) characters in your reference sequence?

-Bryce

**Comment by tadediran** [comment]
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
*****************************************************************************************************************************************
SETTINGS:
|-refgenome:	/Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3/GCA_002795285.1_ASM279528v1_genomic.fna
|-aligner:	libMUSCLE
|-seqdir:	/Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3/MRSA297_6GL/
|-outdir:	/Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3/Clade3_pair_analysis/P_2020_09_17_222317042309
|-OS:		Darwin
|-threads:	32
*****************************************************************************************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from /Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3/MRSA297_6GL/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
ERROR: ref genome sequence /Users/tadediran/Desktop/Parsnp-OSX64-v1.2/Clade_Pair_SNP_analysis/Clade3/GCA_002795285.1_ASM279528v1_genomic.fna seems to aligned! remove and restart

**Comment by bkille** [comment]
@tadediran It looks like you are using an older version of parsnp. Our latest version, 1.5.3, is [available on bioconda](https://bioconda.github.io/recipes/parsnp/README.html)

**Comment by tadediran** [comment]
Unfortunately, I am getting the same error as before

**Comment by bkille** [comment]
Hi @tadediran! Could you share the output from v1.5.3?
