### ISSUE TITLE
error happens when using sample data to test this

### ISSUE THREAD

**Issue by zerodel** [marbl/parsnp#85]
I tried this tool
> parsnp -g ../data/ref.gb -c -d ./single_fa -c -o parsnp_out
and get error message : 
> The following command failed:
> >>/tmp/_MEINReRdi/parsnp parsnp_out/parsnpAligner.ini
> Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.

then I tried this on sample mers data , 

>parsnp -r ./ref/England1.fna -d ./genomes -c

then get  error message as following:

> ERROR: genome sequence Jeddah_2014_C7569.fna seems to aligned! remove and restart

no idea what happens ....

**Comment by bkille** [comment]
Hi @zerodel 

Can you attach the full output of `parsnp`? The sequence `Jeddah_2014_C7569.fna` has inserts (`-`) in it and the old version of parsnp gives up when it sees this, as in your case. This has been fixed in the current version of parsnp, though. See below:

```
|--Parsnp 1.5.3--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
19:09:24 - INFO - 
****************************************************************************************
SETTINGS:
|-refgenome:	examples/mers_virus/ref/England1.fna
|-genomes:	
	examples/mers_virus/genomes/Al-Hasa_1_2013.fna
	examples/mers_virus/genomes/Al-Hasa_12_2013.fna
	...43 more file(s)...
	examples/mers_virus/genomes/Taif_1_2013.fna
	examples/mers_virus/genomes/Wadi-Ad-Dawasir_1_2013.fna
|-aligner:	muscle
|-outdir:	/home/Users/blk6/Projects/HarvestSuite/parsnp/P_2020_09_15_190924438670
|-OS:	Linux
|-threads:	1
****************************************************************************************
    
19:09:24 - INFO - <<Parsnp started>>
19:09:24 - INFO - No genbank file provided for reference annotations, skipping..
19:09:24 - WARNING - Genome sequence examples/mers_virus/genomes/Al-Hasa_4_2013.fna seems to be aligned! Skip!
19:09:24 - ERROR - File examples/mers_virus/genomes/Al-Hasa_ALL.fna is 8.91x longer than reference! Skipping...
19:09:24 - INFO - Recruiting genomes...
19:09:25 - INFO - Running Parsnp multi-MUM search and libMUSCLE aligner...
19:09:25 - INFO - Reconstructing core genome phylogeny...
19:09:30 - INFO - Aligned 46 genomes in 1.34 seconds
19:09:30 - INFO - Parsnp finished! All output available in /home/Users/blk6/Projects/HarvestSuite/parsnp/P_2020_09_15_190924438670
```

**Comment by zerodel** [comment]
@bkille 

Thanks for your reply! 

I reinstalled parsnp, and now it works normally.

**Comment by zerodel** [comment]
another question.

I didn't see the vcf file. 

ggr file ok
tree file ok
xmfa file ok
ini/log , ok

**Comment by zerodel** [comment]
It shows that, parsnp will do output validation at the end of the processing step. 

https://harvest.readthedocs.io/en/latest/content/parsnp/tutorial.html 

>~/bin/parsnp -r ~/project/parsnp/examples/mers_virus/ref/England1.fna -d ~/project/parsnp/examples/mers_virus/genomes -c -o ./out

I get

> |--Parsnp 1.5.3--|
> For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
> 17:42:26 - INFO -
> **********************
> SETTINGS:
> |-refgenome:    /home/zerodel/project/parsnp/examples/mers_virus/ref/England1.fna
> |-genomes:
>         /home/zerodel/project/parsnp/examples/mers_virus/genomes/Al-Hasa_12_2013.fna
>         /home/zerodel/project/parsnp/examples/mers_virus/genomes/Al-Hasa_15_2013.fna
>         ...42 more file(s)...
>         /home/zerodel/project/parsnp/examples/mers_virus/genomes/Taif_1_2013.fna
>         /home/zerodel/project/parsnp/examples/mers_virus/genomes/Wadi-Ad-Dawasir_1_2013.fna
> |-aligner:      muscle
> |-outdir:       ./out
> |-OS:   Linux
> |-threads:      1
> **********************
> 
> 17:42:26 - INFO - <<Parsnp started>>
> 17:42:26 - INFO - No genbank file provided for reference annotations, skipping..
> 17:42:26 - INFO - Running Parsnp multi-MUM search and libMUSCLE aligner...
> 17:42:27 - INFO - Reconstructing core genome phylogeny...
> 17:42:29 - INFO - Aligned 47 genomes in 0.50 seconds
> 17:42:29 - INFO - Parsnp finished! All output available in ./out

Thanks in advance !

**Comment by zerodel** [comment]
ok, seem that parsnp now use harvestools to convert .ggr file into vcf. 

maybe it's better to add it to readme.

Still thanks for this tool , it helps me a lot !
