### ISSUE TITLE
error : CRITICAL -  Profile not in system path!

### ISSUE THREAD

**Issue by aliciacb** [marbl/parsnp#86]
Hello,

I have installed version 1.5.0 (but this error also occurs with 1.5.3), following instructions. 

I run this command:
./parsnp_linux/parsnp -r reference.fasta -d ../../assemblies/ -c

I get this output:
|--Parsnp v1.5--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
16:38:15 - CRITICAL - Profile not in system path!

Any ideas what I am doing wrong? 
Thank you for your help!
Alicia

**Comment by bkille** [comment]
Hi Alicia,

Thanks for using Parsnp! Parsnp has [a number of dependencies](https://github.com/marbl/parsnp#from-source) required for use. Those dependencies must be added to your system path if you are installing from source. Alternatively, if you are installing from conda (recommended), the dependencies will be installed and added to the system path automatically.

**Comment by aliciacb** [comment]
Thank you for such a quick response. I have tried installing harvest both from source and from conda.
When running conda: conda install -c bioconda parsnp.  Only version 1.2 is installed (not the latest 1.5.3). I have tried updating the package but it says 1.2 is the latest on conda. I've also tried with harvesttools but no success either.

**Comment by bkille** [comment]
This will happen bioconda doesn't have the proper channels set up. 

Please see https://bioconda.github.io/user/install.html#set-up-channels

Let me know if this doesn't solve your issue and thanks again for using parsnp!
