### ISSUE TITLE
name 'chr_spos' is not defined in parsnp

### ISSUE THREAD

**Issue by ruchi19flowchart** [marbl/parsnp#87]
**12:02:28 - INFO - <<Parsnp started>>
12:02:28 - INFO - No genbank file provided for reference annotations, skipping..
12:02:29 - INFO - Running Parsnp multi-MUM search and libMUSCLE aligner...
12:08:06 - INFO - Running PhiPack on LCBs to detect recombination...
Traceback (most recent call last):
  File "/opt/app/anaconda/bin/parsnp", line 1321, in <module>
    if block_spos < chr_spos:**

the above error I'm getting when I'm executing the program taking multifasta file as a reference. Running 1.5.3 version.
Kindly check.

**Comment by bkille** [comment]
@ruchi19flowchart Hi! Thanks for bringing this bug to attention and sorry for the inconvenience. There is a new release available (also on bioconda) that should resolve this issue. Note that bioconda version does not have an updated version string (running `parsnp --version` will still show `1.5.3`), however through conda you can verify that the version is indeed 1.5.4. I will be fixing this tonight, though.

**Comment by ruchi19flowchart** [comment]
Thank you so much
