### ISSUE TITLE
No VCF file produced

### ISSUE THREAD

**Issue by mgalardini** [marbl/parsnp#9]
Hi,

thanks a lot for this really interesting and useful software.
In the "Quick start" page of the documentation (http://harvest.readthedocs.org/en/latest/content/parsnp/quickstart.html) the presence of a VCF file is reported i the output directory, but when running the following command I haven't got such thing.

    ./parsnp -g NC_000913.gbk -r genomes/NC_000913.fasta -d genomes -p 10 -v -c

This is the content of the output directory:

    all_mumi.ini         parsnpAligner.ini  parsnp.ggr   parsnp.xmfa
    NC_000913.fasta.ref  parsnpAligner.log  parsnp.tree  psnn.ini

I'm interested in getting the SNPs of the input genomes as compared to the reference; if that information is stored elsewhere I would be happy anyway :)

Thanks a lot,
Marco

**Comment by mgalardini** [comment]
Sorry, just found out about harvesttools to do all the conversions.
Maybe would be good to add this bit of information in the parsnp docs?

Best,
Marco

**Comment by treangen** [comment]
Thanks Marco, this is a good suggestion, I will add additional details to the docs.
