### ISSUE TITLE
conda and pip install don't install the latest version

### ISSUE THREAD

**Issue by tiagocabralborelli** [marbl/parsnp#90]
Recently I had to reinstall parsnp and I realized that neither conda nor pip are downloading version 1.5.4. Instead, they download version 1.2 which presented some bugs even for genomes that I have successfully used before. 
I tried to replace only the parsnp file available on this repository but I'm my Linux abilities are that good. Please can someone give me a hint? 
Thanks.

**Comment by bkille** [comment]
Hi, this seems to be a symptom of not setting up the Bioconda channels. The documentation for setting up Bioconda can be found [here](https://bioconda.github.io/user/install.html#getting-started)

**Comment by tiagocabralborelli** [comment]
I tried set bioconda channel and the version problem remains but with the conda-forge channel, everything seems to be ok and working well. 

Thanks, guys. <3
