### ISSUE TITLE
AcrB mutation in S. Typhi

### ISSUE THREAD

**Issue by fahadkhokhar** [marbl/parsnp#93]
Hello! Uploading genomes to PathogenWatch - it seems that the azithromycin resistance mutation acrB R717L in _S._ Typhi is not being picked up. The R717Q mutation is correctly identified.

**Comment by bkille** [comment]
Hi @fahadkhokhar, sorry for the delay. Can you elaborate on this error a bit more? Are you using Parsnp to align a group of genomes and noticing that the alignment doesn't report the R717L variant?

**Comment by fahadkhokhar** [comment]
Hi, this seems to have been resolved in the latest update from Pathogenwatch.
