### ISSUE TITLE
AttributeError version 1.5.6

### ISSUE THREAD

**Issue by kristij249** [marbl/parsnp#97]
New to all of this, but I just installed parsnp version 1.5.6 and when running the code ./parsnp -r (insert my reference file with path) -d (insert my directory of genomes to align with the path), I get the following error message: 

|--Parsnp 1.5.6--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
Traceback (most recent call last):
  File "./parsnp", line 604, in <module>
    if shutil.which(exe) is None:
AttributeError: 'module' object has no attribute 'which'

**Comment by bkille** [comment]
@kristij249,

Thanks for trying out Parsnp! It looks like you are using Python 2 which has been deprecated as of January 1, 2020, RIP :skull: 

I'd strongly suggest installing `conda` via [miniconda](https://conda.io/projects/conda/en/latest/user-guide/install/index.html#). Once you install miniconda and [update your channels](https://bioconda.github.io/user/install.html#set-up-channels), you can install parsnp via:

`conda install parsnp` 

This is the preferred method of installation, and will also make it easier to keep up with new updates.

**Comment by kristij249** [comment]
@bkille Thank you for your rapid response. It took a while but I did get that. I noticed though that the version of parsnp that is downloaded that way is still version 1.2 in the bin folder? is there a way to update this or am I in the wrong folder for execution?

**Comment by bkille** [comment]
Of course, happy to help. Have you installed via conda? Could you show me the output you're observing?

**Comment by bkille** [comment]
@kristij249 I'm closing this issue as a stale issue. It seems that you've installed parsnp via conda, but are seeing the old version of conda in the `bin/` folder. This is because the version of parsnp that you obtained via conda is in `${CONDA_PREFIX}/bin`. 

Let me know if you still have questions!

-Bryce

**Comment by kristij249** [comment]
Thanks Bryce,
My apologies for not responding to this sooner, I got pulled onto another project. I appreciate your rapid responses and assistance.
Have a good evening,
Kristi

Kristi Jones, Ph. D.
Biological Scientist
Food Animal Reproductive Services
Large Animal Clinical Sciences
University of Florida Vet Med
***@***.******@***.***>
(352)294-4326
