### ISSUE TITLE
autoreconf: error: aclocal failed with exit status: 2

### ISSUE THREAD

**Issue by emmannaemeka** [marbl/parsnp#98]
Hello,
Please am trying to install parsnp on my mac

./autogen.sh
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2
Now run ./configure --prefix=/Users/emmannaemeka && make install
Add --disable-shared to the configure line if building on Mac OS X

Also while running
./configure --prefix=$PWD CXXFLAGS='-fopenmp'

I get

configure: error: cannot find install-sh, install.sh, or shtool in config "."/config

**Comment by bkille** [comment]
Hi @emmannaemeka! Thanks for your interest in parsnp. It looks like you are missing the automake package.

That being said, I'd _highly_ suggest using Bioconda to install parsnp. The instructions are [here](https://bioconda.github.io/user/install.html). FWIW, nearly all major bioinformatics software is primarily installed via bioconda, so this will make installing parsnp easier as well as all future softwares (: 

Happy to answer any questions you have about setting up bioconda and installing parsnp. Thanks!

-Bryce

**Comment by emmannaemeka** [comment]
Thanks Bryce,
I have installed it using bioconda

However, I tried running

parsnp -r  /Users/emmannaemeka/Documents/fastq.gz/T1:44_reference/genome_assemblies_genome_fasta/ncbi-genomes-2021-11-18/genome_assemblies_genome_gb/ncbi-genomes-2021-11-18/GCF_001564435.1_ASM156443v1_genomic.gbff  -d /Users/emmannaemeka/Documents/fastq.gz/genomes -p 4
|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
*********************************************************************************
SETTINGS:
|-refgenome:	/Users/emmannaemeka/Documents/fastq.gz/T1:44_reference/genome_assemblies_genome_fasta/ncbi-genomes-2021-11-18/genome_assemblies_genome_gb/ncbi-genomes-2021-11-18/GCF_001564435.1_ASM156443v1_genomic.gbff
|-aligner:	libMUSCLE
|-seqdir:	/Users/emmannaemeka/Documents/fastq.gz/genomes
|-outdir:	/Users/emmannaemeka/Documents/fastq.gz/P_2021_11_18_234025028701
|-OS:		Darwin
|-threads:	4
*********************************************************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from /Users/emmannaemeka/Documents/fastq.gz/genomes..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
Parsnp requires 2 or more genomes to run, exiting
[] /Users/emmannaemeka/Documents/fastq.gz/P_2021_11_18_234025028701/GCF_001564435.1_ASM156443v1_genomic.gbff.ref

Please can you help?

**Comment by bkille** [comment]
It looks like parsnp v1.2 was installed and not v1.5. This often happens when the conda channels are not set up. Can you confirm that you set up the channels as described [here](https://bioconda.github.io/user/install.html#set-up-channels)?

**Comment by emmannaemeka** [comment]
This was how it was setup

conda config --add channels defaults

conda config --add channels bioconda

conda config --add channels conda-forge

sudo conda install parsnp




Nnaemeka Emmanuel Nnadi,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:

https://orcid.org/0000-0002-8424-4859

 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by bkille** [comment]
Hmmm you should not be using sudo with conda. Can you confirm that you're running Python 3.6 or higher?

**Comment by emmannaemeka** [comment]
which python

/Users/emmannaemeka/miniconda3/bin/python

Python 3.9.5 (default, May 18 2021, 12:31:01)

[Clang 10.0.0 ] :: Anaconda, Inc. on darwin

Type "help", "copyright", "credits" or "license" for more information.


If i just run conda install it will not but ask me to use sudo




Nnaemeka Emmanuel Nnadi,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:

https://orcid.org/0000-0002-8424-4859

 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by bkille** [comment]
There seems to be something wrong with your conda installation. You shouldn't need sudo permissions to install. Either way, could you show me the output of what happens when you run 
```
conda create --name ptest python=3.7 parsnp=1.5
```

**Comment by emmannaemeka** [comment]
## Package Plan ##


  environment location: /Users/emmannaemeka/miniconda3/envs/ptest


  added / updated specs:

    - parsnp=1.5

    - python=3.7



The following packages will be downloaded:


    package                    |            build

    ---------------------------|-----------------

    boost-1.70.0               |   py37hbf1eeb5_1         333 KB
conda-forge

    boost-cpp-1.70.0           |       hef959ae_3        18.9 MB
conda-forge

    fastani-1.32               |       he69ab0f_0         151 KB  bioconda

    fasttree-2.1.10            |       hb4d813b_5         147 KB  bioconda

    harvesttools-1.2           |       h1b062d3_1         684 KB  bioconda

    icu-67.1                   |       hb1e8313_0        12.6 MB
conda-forge

    libffi-3.4.2               |       h0d85af4_5          50 KB
conda-forge

    libgcc-4.8.5               |                1         785 KB
conda-forge

    llvm-openmp-8.0.1          |       h770b8ee_0         253 KB
conda-forge

    mash-1.1                   |                0         250 KB  bioconda

    mkl-service-2.4.0          |   py37hbfd6c52_0          43 KB
conda-forge

    mkl_fft-1.3.1              |   py37h6365bc4_1         176 KB
conda-forge

    mkl_random-1.2.2           |   py37hb23ed4d_0         288 KB
conda-forge

    numpy-1.21.2               |   py37h4b4dc7a_0          23 KB

    numpy-base-1.21.2          |   py37he0bd621_0         4.6 MB

    openmp-8.0.1               |                0           8 KB
conda-forge

    openssl-3.0.0              |       h0d85af4_2         2.5 MB
conda-forge

    parsnp-1.5.4               |       h7475705_0         1.1 MB  bioconda

    phipack-1.1                |       hb4d813b_1          73 KB  bioconda

    pip-21.3.1                 |     pyhd8ed1ab_0         1.2 MB
conda-forge

    python-3.7.12              |hf3644f1_100_cpython        24.3 MB
conda-forge

    python_abi-3.7             |          2_cp37m           4 KB
conda-forge

    raxml-8.2.12               |       hb4d813b_3         2.6 MB  bioconda

    setuptools-59.1.1          |   py37hf985489_0         1.0 MB
conda-forge

    zstd-1.4.9                 |       h582d3a0_0         460 KB
conda-forge

    ------------------------------------------------------------

                                           Total:        72.4 MB


The following NEW packages will be INSTALLED:


  blas               pkgs/main/osx-64::blas-1.0-mkl

  boost              conda-forge/osx-64::boost-1.70.0-py37hbf1eeb5_1

  boost-cpp          conda-forge/osx-64::boost-cpp-1.70.0-hef959ae_3

  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4

  ca-certificates
conda-forge/osx-64::ca-certificates-2021.10.8-h033912b_0

  fastani            bioconda/osx-64::fastani-1.32-he69ab0f_0

  fasttree           bioconda/osx-64::fasttree-2.1.10-hb4d813b_5

  harvesttools       bioconda/osx-64::harvesttools-1.2-h1b062d3_1

  icu                conda-forge/osx-64::icu-67.1-hb1e8313_0

  intel-openmp       pkgs/main/osx-64::intel-openmp-2021.4.0-hecd8cb5_3538

  libcxx             conda-forge/osx-64::libcxx-12.0.1-habf9029_0

  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5

  libgcc             conda-forge/osx-64::libgcc-4.8.5-1

  libzlib            conda-forge/osx-64::libzlib-1.2.11-h9173be1_1013

  llvm-openmp        conda-forge/osx-64::llvm-openmp-8.0.1-h770b8ee_0

  lz4-c              conda-forge/osx-64::lz4-c-1.9.3-he49afe7_1

  mash               bioconda/osx-64::mash-1.1-0

  mkl                pkgs/main/osx-64::mkl-2021.4.0-hecd8cb5_637

  mkl-service        conda-forge/osx-64::mkl-service-2.4.0-py37hbfd6c52_0

  mkl_fft            conda-forge/osx-64::mkl_fft-1.3.1-py37h6365bc4_1

  mkl_random         conda-forge/osx-64::mkl_random-1.2.2-py37hb23ed4d_0

  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4

  numpy              pkgs/main/osx-64::numpy-1.21.2-py37h4b4dc7a_0

  numpy-base         pkgs/main/osx-64::numpy-base-1.21.2-py37he0bd621_0

  openmp             conda-forge/osx-64::openmp-8.0.1-0

  openssl            conda-forge/osx-64::openssl-3.0.0-h0d85af4_2

  parsnp             bioconda/osx-64::parsnp-1.5.4-h7475705_0

  phipack            bioconda/osx-64::phipack-1.1-hb4d813b_1

  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0

  python             conda-forge/osx-64::python-3.7.12-hf3644f1_100_cpython

  python_abi         conda-forge/osx-64::python_abi-3.7-2_cp37m

  raxml              bioconda/osx-64::raxml-8.2.12-hb4d813b_3

  readline           conda-forge/osx-64::readline-8.1-h05e3726_0

  setuptools         conda-forge/osx-64::setuptools-59.1.1-py37hf985489_0

  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0

  sqlite             conda-forge/osx-64::sqlite-3.36.0-h23a322b_2

  tk                 conda-forge/osx-64::tk-8.6.11-h5dbffcc_1

  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1

  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1

  zlib               conda-forge/osx-64::zlib-1.2.11-h9173be1_1013

  zstd               conda-forge/osx-64::zstd-1.4.9-h582d3a0_0



Proceed ([y]/n)? y
Nnaemeka Emmanuel Nnadi,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:

https://orcid.org/0000-0002-8424-4859

 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by emmannaemeka** [comment]
Running

 parsnp -r
/Users/emmannaemeka/Documents/fastq.gz/T1:44_reference/genome_assemblies_genome_fasta/ncbi-genomes-2021-11-18/genome_assemblies_genome_gb/ncbi-genomes-2021-11-18/GCF_001564435.1_ASM156443v1_genomic.gbff
-d /Users/emmannaemeka/Documents/fastq.gz/genomes -p 4

|--Parsnp 1.5.3--|

For detailed documentation please see -->
http://harvest.readthedocs.org/en/latest

07:17:50 - *INFO* -

***********************************************************************************************

SETTINGS:

|-refgenome:
/Users/emmannaemeka/Documents/fastq.gz/T1:44_reference/genome_assemblies_genome_fasta/ncbi-genomes-2021-11-18/genome_assemblies_genome_gb/ncbi-genomes-2021-11-18/GCF_001564435.1_ASM156443v1_genomic.gbff

|-genomes:

/Users/emmannaemeka/Documents/fastq.gz/genomes/sample1.7.fasta

/Users/emmannaemeka/Documents/fastq.gz/genomes/sample_1.4.fasta

...4 more file(s)...

/Users/emmannaemeka/Documents/fastq.gz/genomes/sample1.8.fasta

/Users/emmannaemeka/Documents/fastq.gz/genomes/sample1.9.fasta

|-aligner: muscle

|-outdir:
/Users/emmannaemeka/Documents/programs/parsnp/muscle/P_2021_11_19_071750673095

|-OS: Darwin

|-threads: 4

***********************************************************************************************



07:17:50 - *INFO* - <<Parsnp started>>

07:17:50 - *INFO* - No genbank file provided for reference annotations,
skipping..

07:17:50 - *CRITICAL* - Reference
/Users/emmannaemeka/Documents/fastq.gz/T1:44_reference/genome_assemblies_genome_fasta/ncbi-genomes-2021-11-18/genome_assemblies_genome_gb/ncbi-genomes-2021-11-18/GCF_001564435.1_ASM156443v1_genomic.gbff
has improperly formatted header.






Nnaemeka Emmanuel Nnadi,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:

https://orcid.org/0000-0002-8424-4859

 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by bkille** [comment]
Interesting. It seems to pick up parsnp 1.5 when you do that. I think that python 3.9 is likely too new to be supported. I'd suggest using a python 3.7 environment.

```
conda install python=3.7
conda install parsnp=1.5.6
```
and you should be good to go.

**Comment by bkille** [comment]
I believe for genbank you need to use -g and not -r

Let me know if that helps.

**Comment by emmannaemeka** [comment]
Thanks for your help

Running conda install parsnp=1.5.6

Returns

PackagesNotFoundError: The following packages are not available from
current channels:


  - parsnp=1.5.6


Current channels:


  - https://conda.anaconda.org/conda-forge/osx-64

  - https://conda.anaconda.org/conda-forge/noarch

  - https://conda.anaconda.org/bioconda/osx-64

  - https://conda.anaconda.org/bioconda/noarch

  - https://repo.anaconda.com/pkgs/main/osx-64

  - https://repo.anaconda.com/pkgs/main/noarch

  - https://repo.anaconda.com/pkgs/r/osx-64

  - https://repo.anaconda.com/pkgs/r/noarch


To search for alternate channels that may provide the conda package you're

looking for, navigate to


    https://anaconda.org


and use the search bar at the top of the page.




Nnaemeka Emmanuel Nnadi,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:

https://orcid.org/0000-0002-8424-4859

 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by bkille** [comment]
Ahhh, I see. There is no OSX build for 1.5.6, but there are more recent builds which support OSX.
